/**
 * @module
 * The one reader for values a container can override after the image is built. `config.js`
 * (generated by `docker/docker-entrypoint.d/` at container start, see `docker/nginx.conf`) sets
 * `window.__APP_CONFIG` before the app bundle loads; dev, unit tests and `vite preview` never
 * get a `config.js`, so every read here falls through to its own `import.meta.env.VITE_*`
 * default — the same code path everywhere, never a central config object.
 */

/**
 * The whitelist of deployment values a running container may override. Every value ships to the
 * browser today via the compiled bundle already, so nothing here is or will ever be a secret.
 */
export interface RuntimeConfig {
    API_URL?: string;
    API_SSE?: string;
    APP_NAME?: string;
    LOCALE_TENANT?: string;
    APP_DEFAULT_LOCALE?: string;
    APP_FALLBACK_LOCALE?: string;
    APP_LOG_LEVEL?: string;
    APP_LOG_SCOPES?: string;
    APP_EMPTY_VALUE?: string;
    AXIOS_TIMEOUT?: string;
    MAX_UPLOAD_BYTES?: string;
    FARO_URL?: string;
    FARO_APP_NAME?: string;
    FARO_APP_VERSION?: string;
    FARO_ENVIRONMENT?: string;
    UMAMI_SRC?: string;
    UMAMI_WEBSITE_ID?: string;
}

/**
 * Reads one runtime-configurable value, trimmed, `undefined` when unset or blank — never `''`, so
 * every call site can chain `?? import.meta.env.VITE_X` (or `||`, where the existing read already
 * used it) without a runtime `''` masking that fallback the way an empty build arg used to.
 *
 * @param name - The `RuntimeConfig` key to read.
 * @returns The trimmed value, or `undefined` when `config.js` never loaded or left it unset.
 */
export function runtimeValue(name: keyof RuntimeConfig): string | undefined {
    const value = (globalThis as { __APP_CONFIG?: RuntimeConfig }).__APP_CONFIG?.[name];
    const trimmed = value?.trim();
    return trimmed || undefined;
}
