#!/usr/bin/env tsx
/*
 * Generates the error-code catalogue from `openapi.yaml`'s `x-error-codes` (CT-D5) — a
 * TypeScript constants object plus the union type derived from it.
 *
 * SHARED SCRIPT — byte-identical in both repos of the pair, and both write an `error-codes.ts`
 * beside their other generated contract types. The input is the SAME file in both: `x-error-codes`
 * is collected once, in the backend's bundler, from every module's own fragment, and travels to
 * the frontend as part of the shared `openapi.yaml`.
 *
 * Deliberately a constants object, never a Zod `z.enum(...)`: `errors[].code` stays `type: string`
 * with no `enum` in the contract (CT-D5, Zalando API guideline #112), so a new code is additive,
 * not a breaking response change. This catalogue exists so a call site can write
 * `ERROR_CODES.CART_EMPTY` instead of retyping the string — the compiler catches a typo or a
 * removed code, but nothing here REJECTS a code the contract doesn't (yet) know about.
 *
 * `--check` writes nothing and exits 1 on a mismatch — the same contract every generator in this
 * family keeps.
 *
 * Usage: tsx scripts/contracts/generate-error-codes.ts --out <path> [--check]
 */
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse } from 'yaml';

/** One error code's declaration, as `x-error-codes` holds it. Only `status`/`description` are read; both already carry the WHY in the contract, so neither is repeated in a comment here. */
interface ErrorCodeEntry {
    status: number;
    description: string;
}

interface OpenApiDocument {
    'x-error-codes'?: Record<string, ErrorCodeEntry>;
}

/** The repo root. `import.meta.url` rather than `__dirname`: this script runs as ESM. */
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

/** The bundled root contract this generator reads. */
const INPUT = path.resolve(ROOT, 'openapi.yaml');

/*
 * Reads the required `--out` argument.
 *
 * @returns Absolute path of the file to generate.
 */
const resolveOutputPath = (): string => {
    const flagIndex = process.argv.indexOf('--out');
    const value = flagIndex === -1 ? undefined : process.argv[flagIndex + 1];
    if (!value) {
        console.error('Missing required argument: --out <path>');
        process.exit(1);
    }
    return path.resolve(ROOT, value);
};

const OUTPUT = resolveOutputPath();

/** `--check` compares and reports; without it the file is written. */
const checkOnly = process.argv.includes('--check');

const document = parse(readFileSync(INPUT, 'utf8')) as OpenApiDocument;
const errorCodes = document['x-error-codes'] ?? {};
const codes = Object.keys(errorCodes).toSorted();

/*
 * Renders one property, with the code's own `status`/`description` as its JSDoc — so a call site
 * can hover `ERROR_CODES.CART_EMPTY` and read what it means without leaving the editor.
 *
 * @param code A declared error code.
 * @returns One `key: value` line, its two-line doc comment above it.
 */
const renderRow = (code: string): string => {
    // `Object.hasOwn`, not a nullish check: `codes` is `Object.keys(errorCodes)`, so every one is
    // declared — see `resolveMessagePayloadType` in `generate-asyncapi-types.ts` for the same guard.
    const entry = Object.hasOwn(errorCodes, code) ? errorCodes[code] : undefined;
    const status = entry?.status ?? 0;
    const description = entry?.description ?? '';
    return (
        `    /** ${status} — ${description} */\n` +
        `    ${JSON.stringify(code)}: ${JSON.stringify(code)},`
    );
};

const rows = codes.map((code) => renderRow(code)).join('\n');

const output =
    '// Code generated by `npm run gen:api`. DO NOT EDIT.\n' +
    '/*\n' +
    ' * GENERATED — do not edit manually.\n' +
    ' * Source: openapi.yaml  |  Regenerate: npm run gen:api\n' +
    ' */\n\n' +
    '/** Every error code the contract declares — CT-D5. Open-ended: a new one is additive, never a breaking change. */\n' +
    `export const ERROR_CODES = {\n${rows}\n} as const;\n\n` +
    "/** Any code `errors[].code` may carry. NOT exhaustive at the type level — the contract's own `enum`-free `code: string` is the reason this exists. */\n" +
    'export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];\n';

if (!checkOnly) {
    writeFileSync(OUTPUT, output, 'utf8');
    console.log(`✓ Generated ${OUTPUT}`);
} else if (existsSync(OUTPUT) && readFileSync(OUTPUT, 'utf8') === output) {
    console.log(`✓ ${OUTPUT} is current with openapi.yaml`);
} else {
    console.error(
        `${OUTPUT} is not what openapi.yaml generates.\n` +
            `  Run: npm run gen:api\n` +
            `  Then commit the result.`
    );
    process.exit(1);
}
