/**
 * Pure half of the permission-action generator: read `actions:` out of the shared authorization
 * document, and render the TypeScript that carries it. No filesystem, so a test can walk it.
 *
 * SHARED SCRIPT — byte-identical in both repos of the pair, like `generate-error-codes.ts`.
 * See: docs/tools/permission-actions.md
 */
import { parse } from 'yaml';

/**
 * The `actions:` list of `authorization-keys.yaml`, in declared order.
 *
 * @param yamlText - the whole document
 * @returns the declared actions
 * @throws {Error} when `actions` is missing, empty, not strings, or repeats one
 */
export const readPermissionActions = (yamlText: string): string[] => {
    const document = parse(yamlText) as { actions?: unknown } | null;
    const actions = document?.actions;
    if (!Array.isArray(actions) || actions.length === 0)
        throw new Error('authorization-keys.yaml declares no `actions:` list');
    if (!actions.every((action): action is string => typeof action === 'string'))
        throw new Error('authorization-keys.yaml `actions:` must be a list of strings');
    if (new Set(actions).size !== actions.length)
        throw new Error('authorization-keys.yaml `actions:` repeats an action');
    return actions;
};

/**
 * The generated module: the runtime array and the union type drawn from it.
 *
 * @param actions - the declared actions, in order
 * @returns the file's full text
 */
export const renderPermissionActions = (actions: readonly string[]): string => {
    const rows = actions.map((action) => `    ${JSON.stringify(action)}`).join(',\n');
    return (
        '// Code generated by `npm run gen:api`. DO NOT EDIT.\n' +
        '/*\n' +
        ' * GENERATED — do not edit manually.\n' +
        ' * Source: shared/authorization-keys.yaml `actions:`  |  Regenerate: npm run gen:api\n' +
        ' */\n\n' +
        '/** Every action a permission key may carry, as declared by the shared authorization keys. */\n' +
        `export const PERMISSION_ACTIONS = [\n${rows}\n] as const;\n\n` +
        '/** One of {@link PERMISSION_ACTIONS}. */\n' +
        'export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];\n'
    );
};
