/**
 * @module
 * Pinia store for the feedback module: a public submit action plus the admin's inbox, built on
 * `useStructureCrudApi` the same way users, products and orders are — server-paginated search,
 * a status update, a delete.
 */
import { defineStore } from 'pinia';
import { useCoreStore, useStructureCrudApi } from '@guebbit/vue-toolkit';
import { useServerPageTotal } from '@/ui/composables/use-server-page-total.ts';
import {
    createFeedbackRequest,
    deleteFeedbackRequest,
    searchFeedbackRequests,
    updateFeedbackRequestStatus
} from '@api';
import type {
    CreateFeedbackRequest,
    FeedbackRequest,
    SearchFeedbackRequestsRequest,
    UpdateFeedbackRequestStatusRequest
} from '@types';

/**
 * Search criteria for the inbox, i.e. everything but pagination (which is owned by the toolkit's
 * search state).
 */
type FeedbackFilters = Omit<SearchFeedbackRequestsRequest, 'page' | 'pageSize'>;

/**
 * The contact form's two audiences: anyone may submit, admins read the inbox and move tickets
 * through their statuses.
 *
 * See the products store for the shape — the inbox is declared as a resource like every other
 * admin list, so paging and caching behave the same everywhere.
 */
export const useFeedbackStore = defineStore('feedback', () => {
    /**
     * Shared per-key loading flags, keyed internally by this store's name.
     */
    const { getLoading, setLoading } = useCoreStore();

    /**
     * Record cache, list/pagination state and the inbox's actions, generated by the toolkit's
     * structured-CRUD primitive. No `list`/`get`/`create`: the inbox is only ever read as a
     * search page, and the public submit is not an inbox record (see {@link submitContact}).
     *
     * `search:` is `POST /feedback/search`, never `GET /feedback`: the GET answers
     * `Cache-Control: private, max-age=30`, so a reload inside that window is a browser cache hit
     * that hands back a row just deleted. A POST is never browser-cached.
     */
    const {
        itemDictionary: requests,
        itemList: requestsList,

        filters,
        loading,
        pageCurrent,
        pageSize,
        // Local-only: counts whatever this store already holds, wrong for a server-paginated
        // search. Shadowed below by useServerPageTotal's, built from the response's own count.
        pageTotal: _localOnlyPageTotal,
        pageItemList,

        fetchPage: fetchPaginationRequests,
        watchList: watchSearchRequests,
        updateOne: updateRequest,
        deleteOne: deleteRequest,
        fetchAny
    } = useStructureCrudApi<
        FeedbackRequest,
        string,
        FeedbackFilters,
        never,
        UpdateFeedbackRequestStatusRequest
    >(
        {
            search: (filters, page, pageSize) =>
                searchFeedbackRequests({
                    page,
                    pageSize,
                    text: filters.text,
                    status: filters.status,
                    email: filters.email
                }).then((response) => {
                    captureTotal(response.data.meta.totalPages);
                    return response.data.items;
                }),

            update: (requestId, data) =>
                updateFeedbackRequestStatus(requestId, data).then((response) => response.data),

            remove: (requestId) => deleteFeedbackRequest(requestId)
        },
        { loadingKey: 'feedback', getLoading, setLoading }
    );

    /**
     * `pageTotal` for `search`'s real, server-paginated results — `captureTotal` is called from
     * `search:` above, once its response's `meta.totalPages` is in.
     */
    const { pageTotal, captureTotal } = useServerPageTotal();

    /**
     * Submits the public contact form. Through `fetchAny`, not `createOne`: the visitor never
     * reads the inbox, so there is nothing to cache the created ticket into.
     *
     * @param message - Name (optional), email, subject and message.
     * @returns A promise resolving once the API accepts it.
     */
    const submitContact = (message: CreateFeedbackRequest) =>
        fetchAny(() => createFeedbackRequest(message));

    return {
        requests,
        requestsList,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        submitContact,
        fetchPaginationRequests,
        watchSearchRequests,
        updateRequest,
        deleteRequest
    };
});
