/**
 * @module
 * Pinia store for the feedback module: a public submit action plus the admin's inbox, built on
 * `useStructureCrudApi` the same way users, products and orders are — server-paginated search,
 * a status update, a delete.
 */
import { defineStore } from 'pinia';
import { useStructureCrudApi } from '@guebbit/vue-toolkit';
import type { AxiosRequestConfig } from 'axios';
import { useIdempotencyKey } from '@/infrastructure/http/idempotency.ts';
import { queryClient } from '@/infrastructure/query-client.ts';
import {
    createFeedbackRequest,
    deleteFeedbackRequest,
    searchFeedbackRequests,
    updateFeedbackRequestStatus
} from '@api';
import type {
    CreateFeedbackRequest,
    FeedbackRequest,
    SearchFeedbackRequestsRequest,
    UpdateFeedbackRequestStatusRequest
} from '@types';

/**
 * Search criteria for the inbox, i.e. everything but pagination (which is owned by the toolkit's
 * search state).
 */
type FeedbackFilters = Omit<SearchFeedbackRequestsRequest, 'page' | 'pageSize'>;

/**
 * The contact form's two audiences: anyone may submit, admins read the inbox and move tickets
 * through their statuses.
 *
 * See the products store for the shape — the inbox is declared as a resource like every other
 * admin list, so paging and caching behave the same everywhere.
 */
export const useFeedbackStore = defineStore('feedback', () => {
    /**
     * Record cache, list/pagination state and the inbox's actions, generated by the toolkit's
     * structured-CRUD primitive. No `list`/`get`/`create`: the inbox is only ever read as a
     * search page, and the public submit is not an inbox record (see {@link submitContact}).
     *
     * `search:` is `POST /feedback/search`, never `GET /feedback`: the filters and the page travel
     * in a body, and a POST is never browser-cached, so a reload cannot hand back a row just deleted.
     */
    const {
        itemDictionary: requests,
        itemList: requestsList,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        fetchPage: fetchPaginationRequests,
        watchList: watchSearchRequests,
        updateOne: updateRequest,
        deleteOne: deleteRequest,
        fetchAny
    } = useStructureCrudApi<
        FeedbackRequest,
        string,
        FeedbackFilters,
        never,
        UpdateFeedbackRequestStatusRequest
    >(
        {
            search: (filters, page, pageSize) =>
                searchFeedbackRequests({
                    page,
                    pageSize,
                    text: filters.text,
                    status: filters.status,
                    email: filters.email
                }).then((response) => ({
                    items: response.data.items,
                    totalItems: response.data.meta.totalItems
                })),

            update: (requestId, data) =>
                updateFeedbackRequestStatus(requestId, data).then((response) => response.data),

            remove: (requestId) => deleteFeedbackRequest(requestId)
        },
        { resourceKey: 'feedback', queryClient }
    );

    /**
     * `Idempotency-Key` for `submitContact` (B10) — a network error or a 5xx resends the SAME
     * key, so a lost response never sends the message twice; any other outcome mints a fresh one.
     */
    const contactIdempotencyKey = useIdempotencyKey();

    /**
     * Submits the public contact form. Through `fetchAny`, not `createOne`: the visitor never
     * reads the inbox, so there is nothing to cache the created ticket into.
     *
     * @param message - Name (optional), email, subject and message.
     * @param options - Per-call axios overrides, forwarded to `orvalMutator` — `Contact.vue`
     *  attaches a solved `HumanCheck` token through it: this route is always guarded by
     *  `humanChallengeGate` once a provider is active.
     * @returns A promise resolving once the API accepts it.
     */
    const submitContact = (message: CreateFeedbackRequest, options?: AxiosRequestConfig) =>
        fetchAny(() =>
            createFeedbackRequest(message, contactIdempotencyKey.withKey(options))
                .then((response) => {
                    contactIdempotencyKey.settle();
                    return response;
                })
                .catch((error: unknown) => {
                    contactIdempotencyKey.settle(error);
                    throw error;
                })
        );

    return {
        requests,
        requestsList,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        submitContact,
        fetchPaginationRequests,
        watchSearchRequests,
        updateRequest,
        deleteRequest
    };
});
