/**
 * @module
 * Pinia store built on `useStructureCrudApi` for users CRUD and paginated
 * search, with a multipart branch for create/update when an avatar is
 * attached, plus two hand-written actions: `hardDeleteUser` for the
 * irreversible delete, and `adminDisableTwoFactor` for the audited,
 * no-proof-required 2FA recovery.
 */
import { defineStore } from 'pinia';
import { useStructureCrudApi } from '@guebbit/vue-toolkit';
import { omitNulls } from '@/infrastructure/utils/forms.ts';
import { queryClient } from '@/infrastructure/query-client.ts';
import {
    listUsers,
    searchUsers,
    getUserById,
    createUser as apiCreateUser,
    createUserWithMultipart,
    updateUserById,
    updateUserByIdWithMultipart,
    deleteUserById,
    hardDeleteUserById,
    restoreUserById,
    adminDisableUserTwoFactor as apiAdminDisableUserTwoFactor
} from '@api';
import type { AxiosRequestConfig } from 'axios';
import type {
    User,
    CreateUserRequestMultipart,
    UpdateUserByIdRequest,
    SearchUsersRequest
} from '@types';

/**
 * Search criteria for the users list, i.e. everything but pagination (which is
 * owned by the toolkit's search state).
 *
 * `id` stays a single string here — the filter box searches for one id — and is wrapped into the
 * one-element array `SearchUsersRequest.id` now requires, in `search:` below.
 */
type UsersFilters = Omit<SearchUsersRequest, 'page' | 'pageSize' | 'id'> & { id?: string };

/**
 * `updateUser`'s payload — the merging `PATCH` body plus the optional replacement image. The
 * JSON write body, not the generated multipart request type: that one has no `imageUrl` field at
 * all (a multipart write cannot clear the image today), and this store needs the field to strip a
 * `null` from the optimistic patch below. See `products/store.ts`'s `UpdateProductData` for the
 * same shape.
 */
type UpdateUserData = UpdateUserByIdRequest & { imageUpload?: Blob };

/**
 * Users CRUD, paginated search and avatar upload.
 *
 * See the products store for the shape — the two are deliberately identical apart
 * from their endpoints and filters, which is the point of declaring a resource rather than
 * wiring one.
 */
export const useUsersStore = defineStore('users', () => {
    /**
     * Record cache, list/pagination state and CRUD actions, generated by the
     * toolkit's structured-CRUD primitive from the three type params (entity,
     * id, filters) plus the create/update request shapes.
     */
    const {
        itemDictionary: users,
        itemList: usersList,
        addRecord: addUser,
        selectedIdentifier: selectedUserId,
        selectedRecord: currentUser,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        fetchList: fetchUsers,
        fetchPage: fetchPaginationUsers,
        watchList: watchSearchUsers,
        fetchOne: fetchUser,
        watchOne: watchUser,
        createOne: createUser,
        updateOne: updateUser,
        deleteOne: deleteUser,
        deleteTarget,
        fetchAny
    } = useStructureCrudApi<
        User,
        string,
        UsersFilters,
        CreateUserRequestMultipart,
        UpdateUserData,
        AxiosRequestConfig
    >(
        {
            list: () => listUsers().then((response) => response.data.items),

            search: (filters, page, pageSize) =>
                searchUsers({
                    page,
                    pageSize,
                    text: filters.text,
                    // The API reads a batch of ids; the filter box searches for one.
                    id: filters.id ? [filters.id] : undefined,
                    email: filters.email,
                    username: filters.username,
                    active: filters.active,
                    deleted: filters.deleted
                }).then((response) => ({
                    items: response.data.items,
                    totalItems: response.data.meta.totalItems
                })),

            get: (userId) => getUserById(userId).then((response) => response.data),

            create: ({ imageUpload, ...userData }, options) =>
                (imageUpload
                    ? createUserWithMultipart({ ...userData, imageUpload }, options)
                    : apiCreateUser(userData, options)
                ).then((response) => response.data),

            // PATCH, not PUT (AUDIT_0924 D17d): `UserEdit.vue` sends only the fields its form
            // actually holds (`email`, `password`, an upload) — a PUT's every omitted field would
            // be cleared instead (RFC 9110 §9.3.4), wiping `role`/`active`/etc. on every save.
            update: (userId, { imageUpload, ...userData } = {}, options) =>
                (imageUpload
                    ? updateUserByIdWithMultipart(userId, { ...userData, imageUpload }, options)
                    : updateUserById(userId, userData, options)
                ).then((response) => response.data),

            remove: (userId) => deleteUserById(userId),

            // The new imageUrl comes back from the API; a Blob has no business in store state —
            // this is the MULTIPART request shape, which never carries `imageUrl` itself, only
            // the upload.
            //
            // `locale`/`phone`/`website`/`imageUrl` accept `null` on the wire (clears the field)
            // but the LOCAL `User` never does; `null` reads as "leave the optimistic guess alone"
            // here, since the real clear only takes visible effect once the response `update:`
            // above already waits for lands.
            optimisticPatch: ({
                imageUpload: _uploaded,
                locale,
                phone,
                website,
                imageUrl,
                ...userData
            } = {}) => ({
                ...userData,
                ...omitNulls({ locale, phone, website, imageUrl }, [
                    'locale',
                    'phone',
                    'website',
                    'imageUrl'
                ])
            })
        },
        { resourceKey: 'users', queryClient }
    );

    /**
     * Permanently deletes a user, bypassing the soft delete.
     *
     * `deleteOne` leaves the record in place with `deletedAt` set, which an admin can still see
     * and restore; this removes it outright and cannot be undone. Distinct methods rather than a
     * flag, so the irreversible one is never reached by passing the wrong boolean.
     *
     * @param userId - Identifier of the user to destroy.
     * @returns A promise resolving once the user is gone.
     */
    const hardDeleteUser = (userId: string) =>
        deleteTarget(() => hardDeleteUserById(userId), userId);

    /**
     * Undoes a soft delete — `POST /users/{id}/restore`. A second `deleteUser` never does:
     * DELETE is one-way on the API, and safe to retry. The restored record replaces the cached one.
     *
     * @param userId - Identifier of the user to restore.
     * @returns A promise resolving with the restored user.
     */
    const restoreUser = (userId: string) =>
        fetchAny(() =>
            restoreUserById(userId).then((response) => {
                addUser(response.data);
                return response.data;
            })
        );

    /**
     * Strips a user's second factor with no code required — the admin-assisted recovery path for
     * an admin who lost both their authenticator and their backup codes. Unlike every self-service
     * 2FA mutation, no proof of the factor is asked for; every call is audited server-side, which
     * is what makes skipping that proof safe to expose here at all.
     *
     * `fetchAny` rather than `deleteTarget`: nothing about the USER record is deleted, only a
     * factor on it — `deleteTarget` would evict the record from this store's cache as if the whole
     * user had been removed.
     *
     * `fetchUser(userId, { forced: true })`, not a plain `fetchUser(userId)`: the toolkit's target
     * cache holds a record fresh for an hour (`staleTime`), so a plain re-fetch right after this
     * call would hand back the same cached, still-enabled record `User.vue` just loaded — `forced`
     * treats it as stale and re-asks the server, which is what makes `currentUser.twoFactorEnabledAt`
     * actually flip and the button gated on it (B9, `User.vue`) disappear without a full page reload.
     *
     * @param userId - Identifier of the user whose 2FA is being stripped.
     * @returns A promise resolving once the factor is gone and the record has been force-refetched,
     *  so a cached `currentUser` never lags what the admin just did.
     */
    const adminDisableTwoFactor = (userId: string) =>
        fetchAny(() =>
            apiAdminDisableUserTwoFactor(userId).then(() => fetchUser(userId, { forced: true }))
        );

    return {
        users,
        usersList,
        addUser,
        selectedUserId,
        currentUser,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        fetchUsers,
        fetchPaginationUsers,
        watchSearchUsers,
        fetchUser,
        watchUser,
        createUser,
        updateUser,
        deleteUser,
        hardDeleteUser,
        restoreUser,
        adminDisableTwoFactor
    };
});
