/**
 * @module
 * Pinia store built on `useStructureCrudApi` for users CRUD and paginated
 * search, with a multipart branch for create/update when an avatar is
 * attached, plus two hand-written actions: `hardDeleteUser` for the
 * irreversible delete, and `adminDisableTwoFactor` for the audited,
 * no-proof-required 2FA recovery.
 */
import { defineStore } from 'pinia';
import { useCoreStore, useStructureCrudApi } from '@guebbit/vue-toolkit';
import { useServerPageTotal } from '@/ui/composables/use-server-page-total.ts';
import {
    listUsers,
    searchUsers,
    getUserById,
    createUser as apiCreateUser,
    createUserWithMultipart,
    updateUserById,
    updateUserByIdWithMultipart,
    deleteUserById,
    hardDeleteUserById,
    adminDisableUserTwoFactor as apiAdminDisableUserTwoFactor
} from '@api';
import type { AxiosRequestConfig } from 'axios';
import type {
    User,
    CreateUserRequestMultipart,
    UpdateUserByIdRequestMultipart,
    SearchUsersRequest
} from '@types';

/**
 * Search criteria for the users list, i.e. everything but pagination (which is
 * owned by the toolkit's search state).
 */
type UsersFilters = Omit<SearchUsersRequest, 'page' | 'pageSize'>;

/**
 * Users CRUD, paginated search and avatar upload.
 *
 * See the products store for the shape — the two are deliberately identical apart
 * from their endpoints and filters, which is the point of declaring a resource rather than
 * wiring one.
 */
export const useUsersStore = defineStore('users', () => {
    /**
     * Shared per-key loading flags, keyed internally by this store's name.
     */
    const { getLoading, setLoading } = useCoreStore();

    /**
     * Record cache, list/pagination state and CRUD actions, generated by the
     * toolkit's structured-CRUD primitive from the three type params (entity,
     * id, filters) plus the create/update request shapes.
     */
    const {
        itemDictionary: users,
        itemList: usersList,
        addRecord: addUser,
        selectedIdentifier: selectedUserId,
        selectedRecord: currentUser,

        filters,
        loading,
        pageCurrent,
        pageSize,
        // Local-only: counts whatever this store already holds, wrong for a server-paginated
        // search. Shadowed below by useServerPageTotal's, built from the response's own count.
        pageTotal: _localOnlyPageTotal,
        pageItemList,

        fetchList: fetchUsers,
        fetchPage: fetchPaginationUsers,
        watchList: watchSearchUsers,
        fetchOne: fetchUser,
        watchOne: watchUser,
        createOne: createUser,
        updateOne: updateUser,
        deleteOne: deleteUser,
        deleteTarget,
        fetchAny
    } = useStructureCrudApi<
        User,
        string,
        UsersFilters,
        CreateUserRequestMultipart,
        UpdateUserByIdRequestMultipart,
        AxiosRequestConfig
    >(
        {
            list: () => listUsers().then((response) => response.data.items),

            search: (filters, page, pageSize) =>
                searchUsers({
                    page,
                    pageSize,
                    text: filters.text,
                    id: filters.id,
                    email: filters.email,
                    username: filters.username,
                    active: filters.active
                }).then((response) => {
                    captureTotal(response.data.meta.totalPages);
                    return response.data.items;
                }),

            get: (userId) => getUserById(userId).then((response) => response.data),

            create: ({ imageUpload, ...userData }, options) =>
                (imageUpload
                    ? createUserWithMultipart({ ...userData, imageUpload }, options)
                    : apiCreateUser(userData, options)
                ).then((response) => response.data),

            update: (userId, { imageUpload, ...userData } = {}, options) =>
                (imageUpload
                    ? updateUserByIdWithMultipart(userId, { ...userData, imageUpload }, options)
                    : updateUserById(userId, userData, options)
                ).then((response) => response.data),

            remove: (userId) => deleteUserById(userId),

            // The new imageUrl comes back from the API; a Blob has no business in store state.
            optimisticPatch: ({ imageUpload: _uploaded, ...userData } = {}) => userData
        },
        { getLoading, setLoading }
    );

    /**
     * `pageTotal` for `search`'s real, server-paginated results — `captureTotal` is called from
     * `search:` above, once its response's `meta.totalPages` is in.
     */
    const { pageTotal, captureTotal } = useServerPageTotal();

    /**
     * Permanently deletes a user, bypassing the soft delete.
     *
     * `deleteOne` leaves the record in place with `deletedAt` set, which an admin can still see
     * and toggle back; this removes it outright and cannot be undone. Distinct methods rather than a
     * flag, so the irreversible one is never reached by passing the wrong boolean.
     *
     * @param userId - Identifier of the user to destroy.
     * @returns A promise resolving once the user is gone.
     */
    const hardDeleteUser = (userId: string) =>
        deleteTarget(() => hardDeleteUserById(userId), userId);

    /**
     * Strips a user's second factor with no code required — the admin-assisted recovery path for
     * an owner who lost both their authenticator and their backup codes. Unlike every self-service
     * 2FA mutation, no proof of the factor is asked for; every call is audited server-side, which
     * is what makes skipping that proof safe to expose here at all.
     *
     * `fetchAny` rather than `deleteTarget`: nothing about the USER record is deleted, only a
     * factor on it — `deleteTarget` would evict the record from this store's cache as if the whole
     * user had been removed.
     *
     * @param userId - Identifier of the user whose 2FA is being stripped.
     * @returns A promise resolving once the factor is gone and the record has been refetched, so
     *  a cached `currentUser` never lags what the admin just did.
     */
    const adminDisableTwoFactor = (userId: string) =>
        fetchAny(() => apiAdminDisableUserTwoFactor(userId).then(() => fetchUser(userId)));

    return {
        users,
        usersList,
        addUser,
        selectedUserId,
        currentUser,

        filters,
        loading,
        pageCurrent,
        pageSize,
        pageTotal,
        pageItemList,

        fetchUsers,
        fetchPaginationUsers,
        watchSearchUsers,
        fetchUser,
        watchUser,
        createUser,
        updateUser,
        deleteUser,
        hardDeleteUser,
        adminDisableTwoFactor
    };
});
