// Code generated by `npm run gen:asyncapi`. DO NOT EDIT.
/* eslint-disable @typescript-eslint/naming-convention */
/*
 * GENERATED — do not edit manually.
 * Source: asyncapi.yaml  |  Regenerate: npm run gen:asyncapi
 */

export interface ObservabilityMetricsPayload {
  'timestamp': string;
  'uptimeSeconds': number;
  'memory': AnonymousSchema3;
  'http': AnonymousSchema8;
  'realtime': AnonymousSchema11;
}
export interface AnonymousSchema3 {
  'rss': number;
  'heapUsed': number;
  'heapTotal': number;
  'external': number;
}
export interface AnonymousSchema8 {
  'totalRequests': number;
  'totalErrors': number;
}
export interface AnonymousSchema11 {
  'sseClients': number;
}
export interface OrderIdPayload {
  'orderId': string;
}
export interface OrderCancelledPayload {
  'orderId': string;
  'refund': boolean;
}
export interface PaymentEventPayload {
  'paymentId': string;
  'orderId': string;
}

export type MetricsSnapshotEvent = ObservabilityMetricsPayload;
export type OrderCreatedEvent = OrderIdPayload;
export type OrderCancelledEvent = OrderCancelledPayload;
export type PaymentSucceededEvent = PaymentEventPayload;

/* Channel name constants (canonical identifiers from asyncapi.yaml) */

/* Channel names in the "observability." namespace */
export const OBSERVABILITY_CHANNELS = {
    METRICS_SNAPSHOT: 'observability.metrics.snapshot',
    METRICS_UPDATED: 'observability.metrics.updated',
    HEARTBEAT: 'observability.heartbeat',
} as const;

/* Union of every "observability." channel name */
export type ObservabilityChannel = (typeof OBSERVABILITY_CHANNELS)[keyof typeof OBSERVABILITY_CHANNELS];

/* Channel names in the "order." namespace */
export const ORDER_CHANNELS = {
    CREATED: 'order.created',
    PAID: 'order.paid',
    SHIPPED: 'order.shipped',
    CANCELLED: 'order.cancelled',
} as const;

/* Union of every "order." channel name */
export type OrderChannel = (typeof ORDER_CHANNELS)[keyof typeof ORDER_CHANNELS];

/* Channel names in the "payment." namespace */
export const PAYMENT_CHANNELS = {
    SUCCEEDED: 'payment.succeeded',
    FAILED: 'payment.failed',
} as const;

/* Union of every "payment." channel name */
export type PaymentChannel = (typeof PAYMENT_CHANNELS)[keyof typeof PAYMENT_CHANNELS];

export const REALTIME_SSE_EVENT_NAMES = [
    "observability.heartbeat",
    "observability.metrics.snapshot",
    "observability.metrics.updated",
] as const;
export type SseEventName = (typeof REALTIME_SSE_EVENT_NAMES)[number];
export interface SseEventPayloadMap {
    "observability.heartbeat": ObservabilityMetricsPayload;
    "observability.metrics.snapshot": ObservabilityMetricsPayload;
    "observability.metrics.updated": ObservabilityMetricsPayload;
}
export type SseEventPayload<TEventName extends SseEventName> = SseEventPayloadMap[TEventName];
