// Code generated by `npm run gen:asyncapi`. DO NOT EDIT.
/* eslint-disable @typescript-eslint/naming-convention */
/*
 * GENERATED — do not edit manually.
 * Source: asyncapi.yaml  |  Regenerate: npm run gen:asyncapi
 */

export interface ObservabilityMetricsPayload {
  'timestamp': string;
  'uptimeSeconds': number;
  'memory': AnonymousSchema3;
  'http': AnonymousSchema8;
  'realtime': AnonymousSchema11;
}
export interface AnonymousSchema3 {
  'rss': number;
  'heapUsed': number;
  'heapTotal': number;
  'external': number;
}
export interface AnonymousSchema8 {
  'totalRequests': number;
  'totalErrors': number;
}
export interface AnonymousSchema11 {
  'sseClients': number;
}

export type MetricsSnapshotEvent = ObservabilityMetricsPayload;
export type MetricsUpdatedEvent = ObservabilityMetricsPayload;
export type HeartbeatEvent = ObservabilityMetricsPayload;

/* Channel name constants (canonical identifiers from asyncapi.yaml) */

/* Channel names in the "observability." namespace */
export const OBSERVABILITY_CHANNELS = {
    METRICS_SNAPSHOT: 'observability.metrics.snapshot',
    METRICS_UPDATED: 'observability.metrics.updated',
    HEARTBEAT: 'observability.heartbeat',
} as const;

/* Union of every "observability." channel name */
export type ObservabilityChannel = (typeof OBSERVABILITY_CHANNELS)[keyof typeof OBSERVABILITY_CHANNELS];

export const REALTIME_SSE_EVENT_NAMES = [
    "observability.heartbeat",
    "observability.metrics.snapshot",
    "observability.metrics.updated",
] as const;
export type SseEventName = (typeof REALTIME_SSE_EVENT_NAMES)[number];
export interface SseEventPayloadMap {
    "observability.heartbeat": HeartbeatEvent;
    "observability.metrics.snapshot": MetricsSnapshotEvent;
    "observability.metrics.updated": MetricsUpdatedEvent;
}
export type SseEventPayload<TEventName extends SseEventName> = SseEventPayloadMap[TEventName];
