// Code generated by the paired backend's `contracts:bundle`. DO NOT EDIT.
/**
 * The analytics event names THIS APP emits.
 *
 * ─── Generated in the paired backend, byte-identical here — do not hand-edit ─────────────────
 * Authored as the backend's `analytics.frontend` contract fragment, published by its
 * `contracts:bundle` task and carried across by `sync:frontend`. The identity gate,
 * `check:spec-identity`, fails the build on the commit that forks the two copies.
 * EITHER backend of the pair produces this file, so it names neither one's layout nor its
 * task runner: the BYTES are the contract, and both have to be able to write them.
 * ────────────────────────────────────────────────────────────────────────────────────────────
 *
 * WHY THIS LIST IS SHORT. Both repos write into one Umami website, and each name has exactly one
 * emitter: the server reports what the server knows, the client reports only what the client
 * alone knows. Everything with an API call behind it — signups, logins, cart changes, checkout
 * outcomes, orders, payments — is emitted by the backend, where it cannot be blocked by an
 * extension, lost with the tab, or forged from a console. What is left is what no request can
 * carry: the app's own lifecycle, a token discarded in the browser, and a checkout that never
 * reached the API.
 *
 * The names live in the backend because the two repos share ONE event namespace; declaring them
 * there is what lets a single test prove no client name collides with a server one.
 *
 * A `const` object rather than an `enum`: the frontend's lint requires `E`-prefixed enums and the
 * backend's does not, so no single `enum` satisfies both.
 */
export const analyticsEvents = {
    // Application lifecycle — there is no "app started" on a server that is always started.
    APP_STARTED: 'app_started',
    APP_READY: 'app_ready',

    // Logging out is a client-side token discard; the API has no request to attribute it to.
    USER_LOGGED_OUT: 'user_logged_out',

    // The checkout request that never reached the API — a dropped connection, a request that
    // failed to leave the browser. NOT the twin of `checkout_failed`, which is the server
    // REJECTING a checkout it received and can name a reason for. Two different facts, and the
    // reason they carry two names: merging them would put an outage and a declined card in one
    // bucket, and only one of them is a product problem.
    CHECKOUT_REQUEST_FAILED: 'checkout_request_failed'
} as const;

/** Any name this app can emit. */
export type AnalyticsEventName = (typeof analyticsEvents)[keyof typeof analyticsEvents];
