import { getEcommerceDemoAPI } from '@api';

/**
 * Single instance of the orval-generated API factory.
 * HTTP configuration (base URL, auth, language, refresh logic) lives in
 * httpClient (http.ts), which the apiMutator (apiMutator.ts) delegates to.
 */
export const {
    getHealth,
    getObservabilityEvents,
    getObservabilityHealth,
    getObservabilityMetrics,
    getObservabilityMetricsOverview,
    getObservabilityAuditLogs,
    getAccount,
    requestAccountDelete,
    confirmAccountDelete,
    login,
    signup,
    requestPasswordReset,
    confirmPasswordReset,
    refreshToken,
    refreshTokenWithPath,
    logoutAll,
    deleteExpiredTokens,
    listUsers,
    createUser,
    updateUser,
    deleteUser,
    getUserById,
    updateUserById,
    deleteUserById,
    searchUsers,
    createFeedbackRequest,
    listFeedbackRequests,
    updateFeedbackRequestStatus,
    listProducts,
    createProduct,
    updateProduct,
    deleteProduct,
    getProductById,
    updateProductById,
    deleteProductById,
    searchProducts,
    getCart,
    upsertCartItem,
    clearCart,
    updateCartItemById,
    removeCartItem,
    getCartSummary,
    checkout,
    listOrders,
    createOrder,
    updateOrder,
    deleteOrder,
    searchOrders,
    getOrderById,
    updateOrderById,
    deleteOrderById,
    getOrderInvoice
} = getEcommerceDemoAPI();
