// Code generated by `npm run gen:asyncapi`. DO NOT EDIT.
/* eslint-disable @typescript-eslint/naming-convention */
/*
 * GENERATED — do not edit manually.
 * Source: asyncapi.yaml  |  Regenerate: npm run gen:asyncapi
 */

export interface ObservabilityMetricsPayload {
  'timestamp': string;
  'uptimeSeconds': number;
  'memory': MemoryUsage;
  'http': HttpMetrics;
  'realtime': RealtimeMetrics;
}
export interface MemoryUsage {
  'rss': number;
  'heapUsed': number;
  'heapTotal': number;
  'external': number;
}
export interface HttpMetrics {
  'totalRequests': number;
  'totalErrors': number;
}
export interface RealtimeMetrics {
  'sseClients': number;
}
export interface OrderCreatedEnvelope {
  'type': OrderCreatedEventType;
  'timestamp': string;
  'data': OrderIdPayload;
}
export type OrderCreatedEventType = "order.created";
export interface OrderIdPayload {
  'orderId': string;
}
export interface OrderPaidEnvelope {
  'type': OrderPaidEventType;
  'timestamp': string;
  'data': OrderIdPayload;
}
export type OrderPaidEventType = "order.paid";
export interface OrderShippedEnvelope {
  'type': OrderShippedEventType;
  'timestamp': string;
  'data': OrderIdPayload;
}
export type OrderShippedEventType = "order.shipped";
export interface OrderCancelledEnvelope {
  'type': OrderCancelledEventType;
  'timestamp': string;
  'data': OrderCancelledPayload;
}
export type OrderCancelledEventType = "order.cancelled";
export interface OrderCancelledPayload {
  'orderId': string;
  'refund': boolean;
}
export interface PaymentSucceededEnvelope {
  'type': PaymentSucceededEventType;
  'timestamp': string;
  'data': PaymentEventPayload;
}
export type PaymentSucceededEventType = "payment.succeeded";
export interface PaymentEventPayload {
  'paymentId': string;
  'orderId': string;
}
export interface PaymentFailedEnvelope {
  'type': PaymentFailedEventType;
  'timestamp': string;
  'data': PaymentEventPayload;
}
export type PaymentFailedEventType = "payment.failed";
export interface PaymentRefundedEnvelope {
  'type': PaymentRefundedEventType;
  'timestamp': string;
  'data': PaymentRefundedPayload;
}
export type PaymentRefundedEventType = "payment.refunded";
export interface PaymentRefundedPayload {
  'paymentId': string;
  'orderId': string;
  'refundId': string;
  'amount': number;
  'currency': string;
}
export interface ReturnRequestedEnvelope {
  'type': ReturnRequestedEventType;
  'timestamp': string;
  'data': ReturnRequestedPayload;
}
export type ReturnRequestedEventType = "return.requested";
export interface ReturnRequestedPayload {
  'returnId': string;
  'orderId': string;
  'reason': string;
}
export interface ReturnReceivedEnvelope {
  'type': ReturnReceivedEventType;
  'timestamp': string;
  'data': ReturnReceivedPayload;
}
export type ReturnReceivedEventType = "return.received";
export interface ReturnReceivedPayload {
  'returnId': string;
  'orderId': string;
}
export interface ReturnClosedEnvelope {
  'type': ReturnClosedEventType;
  'timestamp': string;
  'data': ReturnClosedPayload;
}
export type ReturnClosedEventType = "return.closed";
export interface ReturnClosedPayload {
  'returnId': string;
  'orderId': string;
  'refundAmount': number;
  'currency': string;
}

export type MetricsSnapshotEvent = ObservabilityMetricsPayload;
export type MetricsUpdatedEvent = ObservabilityMetricsPayload;
export type HeartbeatEvent = ObservabilityMetricsPayload;
export type OrderCreatedEvent = OrderCreatedEnvelope;
export type OrderPaidEvent = OrderPaidEnvelope;
export type OrderShippedEvent = OrderShippedEnvelope;
export type OrderCancelledEvent = OrderCancelledEnvelope;
export type PaymentSucceededEvent = PaymentSucceededEnvelope;
export type PaymentFailedEvent = PaymentFailedEnvelope;
export type PaymentRefundedEvent = PaymentRefundedEnvelope;
export type ReturnReceivedEvent = ReturnReceivedEnvelope;
export type ReturnClosedEvent = ReturnClosedEnvelope;
export type ReturnRequestedEvent = ReturnRequestedEnvelope;

/* Channel name constants (canonical identifiers from asyncapi.yaml) */

/* Channel names in the "observability." namespace */
export const OBSERVABILITY_CHANNELS = {
    METRICS_SNAPSHOT: 'observability.metrics.snapshot',
    METRICS_UPDATED: 'observability.metrics.updated',
    HEARTBEAT: 'observability.heartbeat',
} as const;

/* Union of every "observability." channel name */
export type ObservabilityChannel = (typeof OBSERVABILITY_CHANNELS)[keyof typeof OBSERVABILITY_CHANNELS];

/* Channel names in the "order." namespace */
export const ORDER_CHANNELS = {
    CREATED: 'order.created',
    PAID: 'order.paid',
    SHIPPED: 'order.shipped',
    CANCELLED: 'order.cancelled',
} as const;

/* Union of every "order." channel name */
export type OrderChannel = (typeof ORDER_CHANNELS)[keyof typeof ORDER_CHANNELS];

/* Channel names in the "payment." namespace */
export const PAYMENT_CHANNELS = {
    SUCCEEDED: 'payment.succeeded',
    FAILED: 'payment.failed',
    REFUNDED: 'payment.refunded',
} as const;

/* Union of every "payment." channel name */
export type PaymentChannel = (typeof PAYMENT_CHANNELS)[keyof typeof PAYMENT_CHANNELS];

/* Channel names in the "return." namespace */
export const RETURN_CHANNELS = {
    REQUESTED: 'return.requested',
    RECEIVED: 'return.received',
    CLOSED: 'return.closed',
} as const;

/* Union of every "return." channel name */
export type ReturnChannel = (typeof RETURN_CHANNELS)[keyof typeof RETURN_CHANNELS];

export const REALTIME_SSE_EVENT_NAMES = [
    "observability.heartbeat",
    "observability.metrics.snapshot",
    "observability.metrics.updated",
] as const;
export type SseEventName = (typeof REALTIME_SSE_EVENT_NAMES)[number];
export interface SseEventPayloadMap {
    "observability.heartbeat": ObservabilityMetricsPayload;
    "observability.metrics.snapshot": ObservabilityMetricsPayload;
    "observability.metrics.updated": ObservabilityMetricsPayload;
}
export type SseEventPayload<TEventName extends SseEventName> = SseEventPayloadMap[TEventName];
export const SSE_EVENT_PAYLOAD_SCHEMAS: Record<SseEventName, Record<string, unknown>> = {
    "observability.heartbeat": {"type":"object","required":["timestamp","uptimeSeconds","memory","http","realtime"],"properties":{"timestamp":{"type":"string","format":"date-time"},"uptimeSeconds":{"type":"integer","minimum":0},"memory":{"title":"MemoryUsage","type":"object","required":["rss","heapUsed","heapTotal","external"],"properties":{"rss":{"type":"integer","minimum":0},"heapUsed":{"type":"integer","minimum":0},"heapTotal":{"type":"integer","minimum":0},"external":{"type":"integer","minimum":0}},"additionalProperties":false},"http":{"title":"HttpMetrics","type":"object","required":["totalRequests","totalErrors"],"properties":{"totalRequests":{"type":"integer","minimum":0},"totalErrors":{"type":"integer","minimum":0}},"additionalProperties":false},"realtime":{"title":"RealtimeMetrics","type":"object","required":["sseClients"],"properties":{"sseClients":{"type":"integer","minimum":0}},"additionalProperties":false}},"additionalProperties":false},
    "observability.metrics.snapshot": {"type":"object","required":["timestamp","uptimeSeconds","memory","http","realtime"],"properties":{"timestamp":{"type":"string","format":"date-time"},"uptimeSeconds":{"type":"integer","minimum":0},"memory":{"title":"MemoryUsage","type":"object","required":["rss","heapUsed","heapTotal","external"],"properties":{"rss":{"type":"integer","minimum":0},"heapUsed":{"type":"integer","minimum":0},"heapTotal":{"type":"integer","minimum":0},"external":{"type":"integer","minimum":0}},"additionalProperties":false},"http":{"title":"HttpMetrics","type":"object","required":["totalRequests","totalErrors"],"properties":{"totalRequests":{"type":"integer","minimum":0},"totalErrors":{"type":"integer","minimum":0}},"additionalProperties":false},"realtime":{"title":"RealtimeMetrics","type":"object","required":["sseClients"],"properties":{"sseClients":{"type":"integer","minimum":0}},"additionalProperties":false}},"additionalProperties":false},
    "observability.metrics.updated": {"type":"object","required":["timestamp","uptimeSeconds","memory","http","realtime"],"properties":{"timestamp":{"type":"string","format":"date-time"},"uptimeSeconds":{"type":"integer","minimum":0},"memory":{"title":"MemoryUsage","type":"object","required":["rss","heapUsed","heapTotal","external"],"properties":{"rss":{"type":"integer","minimum":0},"heapUsed":{"type":"integer","minimum":0},"heapTotal":{"type":"integer","minimum":0},"external":{"type":"integer","minimum":0}},"additionalProperties":false},"http":{"title":"HttpMetrics","type":"object","required":["totalRequests","totalErrors"],"properties":{"totalRequests":{"type":"integer","minimum":0},"totalErrors":{"type":"integer","minimum":0}},"additionalProperties":false},"realtime":{"title":"RealtimeMetrics","type":"object","required":["sseClients"],"properties":{"sseClients":{"type":"integer","minimum":0}},"additionalProperties":false}},"additionalProperties":false},
};
