// Code generated by `npm run gen:api`. DO NOT EDIT.
/*
 * GENERATED — do not edit manually.
 * Source: shared/authorization-keys.yaml `actions:`  |  Regenerate: npm run gen:api
 */

/** Every action a permission key may carry, as declared by the shared authorization keys. */
export const PERMISSION_ACTIONS = [
    "read",
    "create",
    "update",
    "delete",
    "checkout",
    "sweep",
    "override",
    "start",
    "receive"
] as const;

/** One of {@link PERMISSION_ACTIONS}. */
export type PermissionAction = (typeof PERMISSION_ACTIONS)[number];
