import { createRequire } from 'node:module';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { parse } from 'yaml';

/*
 * Load @asyncapi/modelina via CJS interop (the ESM build lacks directory-level re-exports).
 * TypeScriptGenerator: emits TypeScript interfaces/types from a parsed meta-model.
 * AsyncAPIInputProcessor: converts an AsyncAPI 2.x document into modelina's InputMetaModel.
 * defaultModelNameConstraints / defaultPropertyKeyConstraints: factory helpers that let us
 * patch just the rules we need without replacing the whole constraint chain.
 * FormatHelpers: utility formatters (toPascalCase, etc.) used by the model-name constraint.
 */
const require = createRequire(import.meta.url);
const { TypeScriptGenerator, AsyncAPIInputProcessor } = require('@asyncapi/modelina');
const { defaultModelNameConstraints } = require(
    '@asyncapi/modelina/lib/cjs/generators/typescript/constrainer/ModelNameConstrainer.js'
);
const { defaultPropertyKeyConstraints } = require(
    '@asyncapi/modelina/lib/cjs/generators/typescript/constrainer/PropertyKeyConstrainer.js'
);
const { FormatHelpers } = require('@asyncapi/modelina/lib/cjs/helpers/index.js');

/*
 * File paths: read from asyncapi.yaml at the repo root, write to src/types.
 */
const rootPath = path.resolve(import.meta.dirname, '..');
const contractPath = path.resolve(rootPath, 'asyncapi.yaml');
const outputPath = path.resolve(rootPath, 'src/types/realtime.generated.ts');

const asyncapiRaw = await readFile(contractPath, 'utf8');
const asyncapiDocument = parse(asyncapiRaw);

const messages = asyncapiDocument?.components?.messages ?? {};
const channels = asyncapiDocument?.channels ?? {};

/*
 * Build a set of the schema names that live under components/schemas so we can
 * distinguish top-level named models from anonymous sub-models generated by modelina.
 */
const schemaNameSet = new Set(
    Object.keys(asyncapiDocument?.components?.schemas ?? {}).map(
        (name) => `I${FormatHelpers.toPascalCase(name)}`
    )
);

/*
 * Configure @asyncapi/modelina TypeScript generator:
 *   - modelType 'interface': emit `interface` declarations instead of classes.
 *   - enumType 'union': emit string-literal union types (e.g. `"chat:join"`) instead of
 *     TypeScript `enum` blocks, keeping values directly assignable from string literals.
 *   - Custom model-name constraint: prepend `I` so generated names match this project's
 *     interface naming convention (enforced by ESLint `/^I[A-Z]/u`).
 *   - Custom property-key constraint: disable the reserved-keyword renaming so that the
 *     `type` property (a valid TS interface member) is NOT renamed to `reservedType`.
 */
const generator = new TypeScriptGenerator({
    modelType: 'interface',
    enumType: 'union',
    constraints: {
        modelName: defaultModelNameConstraints({
            NAMING_FORMATTER: (value) => `I${FormatHelpers.toPascalCase(value)}`
        }),
        propertyKey: defaultPropertyKeyConstraints({
            NO_RESERVED_KEYWORDS: (value) => value
        })
    }
});

/*
 * Parse the full AsyncAPI document into modelina's intermediate representation, then
 * generate all TypeScript models (named schemas + anonymous sub-schemas for nested objects).
 */
const processor = new AsyncAPIInputProcessor();
const inputModel = await processor.process(asyncapiDocument);
const allModels = await generator.generate(inputModel);

/*
 * Collect every model that is transitively referenced by the named component schemas.
 * This includes the named models themselves and any IAnonymousSchema_N sub-types they
 * reference for nested objects/enums.  Message-payload anonymous models are excluded here
 * because message types are handled separately below.
 */
const collectTransitiveRefs = (startNames, modelsByName) => {
    const visited = new Set(startNames);
    const queue = [...startNames];

    while (queue.length > 0) {
        const name = queue.shift();
        const model = modelsByName.get(name);
        if (!model) continue;

        // Extract all IAnonymousSchema_N identifiers referenced inside this model's source
        const refs = model.result.match(/\bI[A-Za-z]\w*\b/g) ?? [];
        for (const ref of refs) {
            if (!visited.has(ref)) {
                visited.add(ref);
                queue.push(ref);
            }
        }
    }

    return visited;
};

const modelsByName = new Map(allModels.map((m) => [m.modelName, m]));
const requiredModelNames = collectTransitiveRefs(schemaNameSet, modelsByName);

/*
 * Emit the schema section: named component schemas and their anonymous sub-types,
 * each prefixed with `export` so consumers can import them by name.
 */
const schemaTypeBlocks = allModels
    .filter((m) => requiredModelNames.has(m.modelName))
    .map((m) => `export ${m.result}`);

/*
 * Message type blocks: one alias per AsyncAPI message.
 *   - Payload via $ref  → simple type alias to the already-generated named schema.
 *   - Inline payload    → custom schemaToType converts the raw JSON Schema object to an
 *     inline TypeScript type literal, avoiding opaque anonymous names in message aliases.
 */
const formatPropertyKey = (property) =>
    /^[A-Za-z_$][A-Za-z0-9_$]*$/u.test(property) ? property : `'${property}'`;

const refToTypeName = (ref) => `I${ref.split('/').pop()}`;

/** Recursively converts a JSON Schema node into a TypeScript type string. */
const schemaToType = (schema, depth = 0) => {
    const indentation = '    '.repeat(depth);
    const childIndentation = '    '.repeat(depth + 1);

    if (schema === null || schema === undefined) return 'unknown';
    if (schema.$ref) return refToTypeName(schema.$ref);

    if (Array.isArray(schema.oneOf))
        return schema.oneOf.map((option) => schemaToType(option, depth)).join(' | ');

    if (Array.isArray(schema.anyOf))
        return schema.anyOf.map((option) => schemaToType(option, depth)).join(' | ');

    if (Array.isArray(schema.allOf))
        return schema.allOf.map((option) => schemaToType(option, depth)).join(' & ');

    if (Array.isArray(schema.enum) && schema.enum.length > 0)
        return schema.enum.map((value) => JSON.stringify(value)).join(' | ');

    if (schema.type === 'array') return `(${schemaToType(schema.items, depth)})[]`;

    if (schema.type === 'object' || schema.properties || schema.additionalProperties) {
        const requiredSet = schema.required ? new Set(schema.required) : undefined;
        const properties = Object.entries(schema.properties ?? {}).map(([key, propSchema]) => {
            const safeKey = formatPropertyKey(key);
            const optional = requiredSet?.has(key) ? '' : '?';
            return `${childIndentation}${safeKey}${optional}: ${schemaToType(propSchema, depth + 1)};`;
        });

        if (typeof schema.additionalProperties === 'object' && !Array.isArray(schema.additionalProperties))
            properties.push(
                `${childIndentation}[key: string]: ${schemaToType(schema.additionalProperties, depth + 1)};`
            );

        if ((schema.additionalProperties === true || schema.additionalProperties === undefined) && properties.length === 0)
            return 'Record<string, unknown>';

        return `{\n${properties.join('\n')}\n${indentation}}`;
    }

    if (schema.type === 'integer' || schema.type === 'number') return 'number';
    if (schema.type === 'boolean') return 'boolean';
    if (schema.type === 'string') return 'string';

    return 'unknown';
};

const messageTypeBlocks = Object.entries(messages).map(([messageName, message]) => {
    const typeName = `I${messageName}`;
    // $ref payload: reuse the already-generated named schema type
    if (message.payload?.$ref) return `export type ${typeName} = ${refToTypeName(message.payload.$ref)};`;
    // Inline payload: expand the schema inline to keep the alias self-contained
    return `export type ${typeName} = ${schemaToType(message.payload, 0)};`;
});

/*
 * Channel name union: only the realtime/observability channels are relevant to the
 * frontend (SSE + WebSocket).  Worker and cache channels are backend-only.
 */
const realtimeChannels = Object.keys(channels).filter(
    (channel) => channel.startsWith('realtime.') || channel.startsWith('observability.')
);

const realtimeChannelUnion =
    realtimeChannels.length > 0
        ? realtimeChannels.map((channel) => JSON.stringify(channel)).join(' | ')
        : 'never';

const generatedSource = `/*
 * This file is auto-generated from asyncapi.yaml via @asyncapi/modelina.
 * Run \`npm run genasyncapi\` after AsyncAPI contract changes.
 */

${schemaTypeBlocks.join('\n\n')}

${messageTypeBlocks.join('\n\n')}

export type IRealtimeChannelName = ${realtimeChannelUnion};
`;

await writeFile(outputPath, generatedSource, 'utf8');
