// Code generated by `npm run gen:api`. DO NOT EDIT.
/*
 * GENERATED — do not edit manually.
 * Source: openapi.yaml  |  Regenerate: npm run gen:api
 */

/** Every error code the contract declares. Open-ended: a new one is additive, never a breaking change. */
export const ERROR_CODES = {
    /** 404 — No challenge is currently active for this session. */
    ANTIBOT_NO_CHALLENGE: 'ANTIBOT_NO_CHALLENGE',
    /** 401 — The human-challenge token is missing, expired, or the provider rejected it. */
    ANTIBOT_VERIFICATION_FAILED: 'ANTIBOT_VERIFICATION_FAILED',
    /** 400 — A malformed request the body parser or a library refused before any route ran. */
    BAD_REQUEST: 'BAD_REQUEST',
    /** 409 — Nothing in this checkout ships to an address (all-digital, or a method that ships to none), so a shipping `addressId` cannot apply. */
    CART_ADDRESS_NOT_APPLICABLE: 'CART_ADDRESS_NOT_APPLICABLE',
    /** 404 — The named address does not exist, or does not belong to the caller. */
    CART_ADDRESS_NOT_FOUND: 'CART_ADDRESS_NOT_FOUND',
    /** 422 — A shipping address is required and none was supplied or found on file. */
    CART_ADDRESS_REQUIRED: 'CART_ADDRESS_REQUIRED',
    /** 409 — This order total exceeds the bank-transfer payment method's configured ceiling. */
    CART_BANK_TRANSFER_LIMIT: 'CART_BANK_TRANSFER_LIMIT',
    /** 422 — No billing address could be resolved — none was named, nothing ships, and the address book has no default. */
    CART_BILLING_ADDRESS_REQUIRED: 'CART_BILLING_ADDRESS_REQUIRED',
    /** 409 — The cart changed between the request that read it and this write — reload and retry. */
    CART_CHANGED: 'CART_CHANGED',
    /** 409 — Checkout was attempted on a cart with no lines. */
    CART_EMPTY: 'CART_EMPTY',
    /** 409 — One or more lines exceed the product's available stock — see `errors[].details.lines`. */
    CART_INSUFFICIENT_STOCK: 'CART_INSUFFICIENT_STOCK',
    /** 409 — The chosen payment method is not enabled for this deployment or this cart. */
    CART_PAYMENT_METHOD_NOT_AVAILABLE: 'CART_PAYMENT_METHOD_NOT_AVAILABLE',
    /** 409 — A line references a product that was deleted or deactivated since it was added. */
    CART_PRODUCT_UNAVAILABLE: 'CART_PRODUCT_UNAVAILABLE',
    /** 422 — The requested quantity exceeds the per-line limit. */
    CART_QUANTITY_LIMIT: 'CART_QUANTITY_LIMIT',
    /** 404 — The named shipping method does not exist or is not offered. */
    CART_SHIPPING_METHOD_NOT_FOUND: 'CART_SHIPPING_METHOD_NOT_FOUND',
    /** 422 — A shipping method is required and none is set on the cart. */
    CART_SHIPPING_METHOD_REQUIRED: 'CART_SHIPPING_METHOD_REQUIRED',
    /** 409 — The cart's total weight falls outside the chosen shipping method's configured range. */
    CART_SHIPPING_METHOD_WEIGHT: 'CART_SHIPPING_METHOD_WEIGHT',
    /** 409 — The chosen shipping method does not apply to an all-digital cart. */
    CART_SHIPPING_NOT_APPLICABLE: 'CART_SHIPPING_NOT_APPLICABLE',
    /** 422 — The address's country is outside this deployment's configured ship-to list. */
    CART_SHIP_TO_COUNTRY_NOT_SUPPORTED: 'CART_SHIP_TO_COUNTRY_NOT_SUPPORTED',
    /** 409 — The request is well-formed but conflicts with the resource's current state. */
    CONFLICT: 'CONFLICT',
    /** 422 — An admin status override requires a reason and none was supplied. */
    DELIVERY_OVERRIDE_REASON_REQUIRED: 'DELIVERY_OVERRIDE_REASON_REQUIRED',
    /** 422 — Marking a shipment shipped requires a tracking code and none was supplied. */
    DELIVERY_TRACKING_CODE_REQUIRED: 'DELIVERY_TRACKING_CODE_REQUIRED',
    /** 403 — Checkout requires a verified email address — see `POST /account/verify-email`. */
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    /** 429 — A verification email was already sent recently — carries `details.retryAfter`. */
    EMAIL_VERIFY_RESEND_TOO_SOON: 'EMAIL_VERIFY_RESEND_TOO_SOON',
    /** 403 — The caller is authenticated but lacks the permission this route requires. A key's own `deniedCode` can replace this default with a more specific one. */
    FORBIDDEN: 'FORBIDDEN',
    /** 409 — Another request already carries this `Idempotency-Key` and has not finished yet. */
    IDEMPOTENCY_IN_FLIGHT: 'IDEMPOTENCY_IN_FLIGHT',
    /** 422 — This `Idempotency-Key` was already used with a different request body. */
    IDEMPOTENCY_KEY_MISMATCH: 'IDEMPOTENCY_KEY_MISMATCH',
    /** 500 — An unexpected server-side failure. Never carries library or stack detail. */
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    /** 422 — A 4xx nobody handled on the way, answered by the global error handler with no copy of its own: a driver failure that is really about the request (a refused write is a 422, a duplicate key a 409, a stale `If-Match` a 412) or a library declaring its own 4xx. A route that catches the failure answers with the status-derived code instead. */
    INVALID_REQUEST: 'INVALID_REQUEST',
    /** 409 — The requested on-hand count is below what is already reserved by open orders. */
    INVENTORY_BELOW_RESERVED: 'INVENTORY_BELOW_RESERVED',
    /** 400 — A multipart upload carries too many non-file fields (multer). */
    LIMIT_FIELD_COUNT: 'LIMIT_FIELD_COUNT',
    /** 400 — A multipart field name is too long (multer). */
    LIMIT_FIELD_KEY: 'LIMIT_FIELD_KEY',
    /** 400 — A multipart field value is too long (multer). */
    LIMIT_FIELD_VALUE: 'LIMIT_FIELD_VALUE',
    /** 400 — A multipart upload carries too many files (multer). */
    LIMIT_FILE_COUNT: 'LIMIT_FILE_COUNT',
    /** 400 — An uploaded file exceeds this deployment's size limit (multer). */
    LIMIT_FILE_SIZE: 'LIMIT_FILE_SIZE',
    /** 400 — A multipart upload carries too many parts (multer). */
    LIMIT_PART_COUNT: 'LIMIT_PART_COUNT',
    /** 400 — A multipart upload carries a file under a field name this operation does not accept (multer). */
    LIMIT_UNEXPECTED_FILE: 'LIMIT_UNEXPECTED_FILE',
    /** 400 — A multipart file part carries no field name (multer). */
    MISSING_FIELD_NAME: 'MISSING_FIELD_NAME',
    /** 404 — The addressed resource does not exist, or the caller may not be told that it does. */
    NOT_FOUND: 'NOT_FOUND',
    /** 404 — The order exists but has no such credit note. */
    ORDER_CREDIT_NOTE_NOT_ISSUED: 'ORDER_CREDIT_NOTE_NOT_ISSUED',
    /** 409 — An admin-created order references a quantity beyond the product's available stock. */
    ORDER_INSUFFICIENT_STOCK: 'ORDER_INSUFFICIENT_STOCK',
    /** 409 — This action is not allowed once an order has been invoiced. */
    ORDER_INVOICED: 'ORDER_INVOICED',
    /** 404 — The order exists but no invoice has been issued for it yet. */
    ORDER_INVOICE_NOT_ISSUED: 'ORDER_INVOICE_NOT_ISSUED',
    /** 409 — The order has no physical lines left to ship. */
    ORDER_NOTHING_TO_SHIP: 'ORDER_NOTHING_TO_SHIP',
    /** 409 — The order is not in a state that can still be cancelled. */
    ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
    /** 409 — This action only applies to an order with no physical lines. */
    ORDER_NOT_DIGITAL_ONLY: 'ORDER_NOT_DIGITAL_ONLY',
    /** 409 — The order must be paid before this delivery action. */
    ORDER_NOT_PAID: 'ORDER_NOT_PAID',
    /** 409 — The order is not in a state this delivery action can run from. */
    ORDER_NOT_PROCESSING: 'ORDER_NOT_PROCESSING',
    /** 409 — The order must be shipped before this delivery action. */
    ORDER_NOT_SHIPPED: 'ORDER_NOT_SHIPPED',
    /** 409 — This status transition is not on the admin override's allowed list. */
    ORDER_OVERRIDE_NOT_ALLOWED: 'ORDER_OVERRIDE_NOT_ALLOWED',
    /** 409 — A line on this order references a product that was deleted or deactivated since the intent was created. */
    ORDER_PRODUCT_UNAVAILABLE: 'ORDER_PRODUCT_UNAVAILABLE',
    /** 413 — The request body exceeds this deployment's size limit. */
    PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
    /** 409 — The card issuer or gateway declined the charge. */
    PAYMENT_DECLINED: 'PAYMENT_DECLINED',
    /** 409 — Another payment attempt for this order is already being recorded. */
    PAYMENT_IN_FLIGHT: 'PAYMENT_IN_FLIGHT',
    /** 409 — The payment is not in a state this confirmation can apply to. */
    PAYMENT_NOT_CONFIRMABLE: 'PAYMENT_NOT_CONFIRMABLE',
    /** 409 — The payment is not in a state that can still be refunded, or nothing of it is left to refund. */
    PAYMENT_NOT_REFUNDABLE: 'PAYMENT_NOT_REFUNDABLE',
    /** 409 — The order is not in a state that can still accept a payment. */
    PAYMENT_ORDER_NOT_PAYABLE: 'PAYMENT_ORDER_NOT_PAYABLE',
    /** 422 — The refund asks for more than the payment still has left to give back. */
    PAYMENT_REFUND_EXCEEDS_REMAINING: 'PAYMENT_REFUND_EXCEEDS_REMAINING',
    /** 412 — The write's `If-Match` no longer describes the stored resource — someone changed or removed it since the caller read it. Re-read, reapply the edit, resend. */
    PRECONDITION_FAILED: 'PRECONDITION_FAILED',
    /** 429 — The caller exceeded a rate-limit budget. Carries a `Retry-After` hint. */
    RATE_LIMITED: 'RATE_LIMITED',
    /** 401 — This action requires a session fresher than the caller's current one — see `POST /account/reauth`. */
    REAUTH_REQUIRED: 'REAUTH_REQUIRED',
    /** 409 — The past order named for reorder no longer has any purchasable lines. */
    REORDER_UNAVAILABLE: 'REORDER_UNAVAILABLE',
    /** 422 — A 4xx with no more specific code of its own. Mostly a 422 refused for a reason that is not one field (a field-level failure is `VALIDATION_ERROR`); also a 429 and any other 4xx the status table does not name. */
    REQUEST_ERROR: 'REQUEST_ERROR',
    /** 422 — The handling deduction is more than the refund is worth. */
    RETURN_DEDUCTION_INVALID: 'RETURN_DEDUCTION_INVALID',
    /** 422 — A line names a product that is not on the order, asks for more than is left of it, is excluded from the right of withdrawal (Art. 16), or nothing on the order is left to return. */
    RETURN_LINES_INVALID: 'RETURN_LINES_INVALID',
    /** 409 — The return has already been decided. */
    RETURN_NOT_DECIDABLE: 'RETURN_NOT_DECIDABLE',
    /** 409 — The return is not an approved one awaiting its goods. */
    RETURN_NOT_RECEIVABLE: 'RETURN_NOT_RECEIVABLE',
    /** 409 — The order is not in a state a return can be opened on — cancelled, or (for a reason other than withdrawal) still in the shop's hands. */
    RETURN_ORDER_NOT_RETURNABLE: 'RETURN_ORDER_NOT_RETURNABLE',
    /** 409 — The withdrawal period for this order has ended. */
    RETURN_WINDOW_CLOSED: 'RETURN_WINDOW_CLOSED',
    /** 503 — A dependency (database, broker) is unreachable. Carries a `Retry-After` hint. */
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    /** 429 — A two-factor code was already sent recently — carries `details.retryAfter`. */
    TWO_FACTOR_RESEND_TOO_SOON: 'TWO_FACTOR_RESEND_TOO_SOON',
    /** 401 — No valid session — log in and retry. */
    UNAUTHORIZED: 'UNAUTHORIZED',
    /** 415 — The request's `Content-Type` is not one this operation accepts. */
    UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
    /** 422 — One or more fields failed schema validation — see `errors[].details.field`. */
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    /** 409 — A retry of this delivery is already in flight. */
    WEBHOOK_DELIVERY_IN_PROGRESS: 'WEBHOOK_DELIVERY_IN_PROGRESS'
} as const;

/** Any code `errors[].code` may carry. NOT exhaustive at the type level — the contract's own `enum`-free `code: string` is the reason this exists. */
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
