/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import { orvalMutator } from '../../src/plugins/http/index.js';
/**
 * 1-based page index
 * @minimum 1
 */
export type Page = number;

/**
 * Optional override; server may clamp to a max
 * @minimum 1
 * @maximum 100
 */
export type PageSize = number;

/**
 * Resource identifier
 */
export type Id = string;

/**
 * Free-text search string
 * @minLength 1
 */
export type Text = string;

export type Email = string;

/**
 * @minLength 8
 */
export type Password = string;

export interface PaginationMeta {
    page: Page;
    pageSize: PageSize;
    /** @minimum 0 */
    totalItems: number;
    /** @minimum 0 */
    totalPages: number;
}

export interface MessageResponse {
    success: true;
    status: number;
    message: string;
}

/**
 * Optional structured metadata for programmatic handling
 */
export type ErrorItemDetails = { [key: string]: unknown };

export interface ErrorItem {
    /** Stable machine-readable error code */
    code: string;
    /** Human-readable error detail */
    message: string;
    /** Optional structured metadata for programmatic handling */
    details?: ErrorItemDetails;
}

export interface ErrorResponse {
    success: false;
    status: number;
    /** Human-readable summary for this failure */
    message: string;
    /**
     * Structured machine-friendly errors
     * @minItems 1
     */
    errors: ErrorItem[];
}

export type ValidationErrorResponse = ErrorResponse & {
    message?: string;
};

export interface SuccessEnvelope {
    success: true;
    status: number;
    message: string;
}

export interface AuthTokens {
    /** Access JWT */
    token: string;
    /** Refresh token if returned by backend */
    refreshToken?: string;
    /** Access token expiry in seconds */
    expiresIn?: number;
}

export type AuthTokensEnvelope = SuccessEnvelope & {
    data: AuthTokens;
};

export interface RefreshTokenResponse {
    /** New access JWT */
    token: string;
    /** New refresh token if returned by backend */
    refreshToken?: string;
    /** New access token expiry in seconds */
    expiresIn?: number;
}

export type RefreshTokenEnvelope = SuccessEnvelope & {
    data: RefreshTokenResponse;
};

export interface User {
    id: Id;
    email: Email;
    username: string;
    admin?: boolean;
    active?: boolean;
    imageUrl?: string;
    createdAt?: string;
    updatedAt?: string;
}

export type UserEnvelope = SuccessEnvelope & {
    data: User;
};

export interface UsersResponse {
    items: User[];
    meta: PaginationMeta;
}

export type UsersResponseEnvelope = SuccessEnvelope & {
    data: UsersResponse;
};

export interface Product {
    id: Id;
    title: string;
    /** @minimum 0 */
    price: number;
    description?: string;
    active?: boolean;
    imageUrl?: string;
    categories?: string[];
    tags?: string[];
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
}

export type ProductEnvelope = SuccessEnvelope & {
    data: Product;
};

export interface ProductsResponse {
    items: Product[];
    meta: PaginationMeta;
}

export type ProductsResponseEnvelope = SuccessEnvelope & {
    data: ProductsResponse;
};

export interface OrderItem {
    product: Product;
    /** @minimum 1 */
    quantity: number;
}

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus];

export const OrderStatus = {
    pending: 'pending',
    paid: 'paid',
    processing: 'processing',
    shipped: 'shipped',
    delivered: 'delivered',
    cancelled: 'cancelled'
} as const;

export interface Order {
    id: Id;
    userId: Id;
    email: Email;
    items: OrderItem[];
    /** @minimum 0 */
    total: number;
    /** Optional order notes */
    notes?: string;
    status: OrderStatus;
    createdAt?: string;
    updatedAt?: string;
}

export type OrderEnvelope = SuccessEnvelope & {
    data: Order;
};

export interface OrdersResponse {
    items: Order[];
    meta: PaginationMeta;
}

export type OrdersResponseEnvelope = SuccessEnvelope & {
    data: OrdersResponse;
};

export type FeedbackRequestStatus =
    (typeof FeedbackRequestStatus)[keyof typeof FeedbackRequestStatus];

export const FeedbackRequestStatus = {
    new: 'new',
    in_progress: 'in_progress',
    resolved: 'resolved',
    spam: 'spam'
} as const;

export interface FeedbackRequest {
    id: Id;
    name?: string;
    email: Email;
    subject: string;
    message: string;
    status: FeedbackRequestStatus;
    adminNotes?: string;
    respondedAt?: string;
    createdAt: string;
    updatedAt?: string;
}

export type FeedbackRequestEnvelope = SuccessEnvelope & {
    data: FeedbackRequest;
};

export interface FeedbackRequestsResponse {
    items: FeedbackRequest[];
    meta: PaginationMeta;
}

export type FeedbackRequestsResponseEnvelope = SuccessEnvelope & {
    data: FeedbackRequestsResponse;
};

export interface CartItem {
    productId: Id;
    /** @minimum 1 */
    quantity: number;
}

export interface CartSummaryResponse {
    /**
     * Number of distinct cart lines/items
     * @minimum 0
     */
    itemsCount: number;
    /**
     * Sum of quantities across all items
     * @minimum 0
     */
    totalQuantity: number;
    /**
     * Sum of item prices * quantity (before tax/shipping/discounts)
     * @minimum 0
     */
    total: number;
    /** ISO-4217 currency code (e.g. USD) */
    currency?: string;
}

export interface CartResponse {
    items: CartItem[];
    summary: CartSummaryResponse;
}

export type CartResponseEnvelope = SuccessEnvelope & {
    data: CartResponse;
};

export type CartSummaryResponseEnvelope = SuccessEnvelope & {
    data: CartSummaryResponse;
};

export interface CheckoutResponse {
    order: Order;
    message?: string;
}

export type CheckoutResponseEnvelope = SuccessEnvelope & {
    data: CheckoutResponse;
};

export type ObservabilityHealthStatus =
    (typeof ObservabilityHealthStatus)[keyof typeof ObservabilityHealthStatus];

export const ObservabilityHealthStatus = {
    ok: 'ok',
    degraded: 'degraded'
} as const;

export type ObservabilityHealthDatabaseStatus =
    (typeof ObservabilityHealthDatabaseStatus)[keyof typeof ObservabilityHealthDatabaseStatus];

export const ObservabilityHealthDatabaseStatus = {
    connected: 'connected',
    connecting: 'connecting',
    disconnected: 'disconnected'
} as const;

export interface ObservabilityHealthIntegrations {
    loki?: boolean;
    posthog?: boolean;
    otelEnabled?: boolean;
    umami?: boolean;
    faro?: boolean;
}

export interface ObservabilityHealthMemory {
    heapUsedMb: number;
    heapTotalMb: number;
    rssMb: number;
}

export interface ObservabilityHealthSystem {
    platform: string;
    cpuCount: number;
    loadAvg: number[];
}

export type ObservabilityHealthDatabase = {
    status: ObservabilityHealthDatabaseStatus;
};

export interface ObservabilityHealth {
    status: ObservabilityHealthStatus;
    environment: string;
    service: string;
    nodeVersion: string;
    /** @minimum 0 */
    uptimeSeconds: number;
    database: ObservabilityHealthDatabase;
    integrations?: ObservabilityHealthIntegrations;
    memory?: ObservabilityHealthMemory;
    system?: ObservabilityHealthSystem;
    timestamp: string;
}

export interface ObservabilityHealthResponse {
    success: true;
    data: ObservabilityHealth;
}

export type ObservabilityHealthResponseEnvelope = SuccessEnvelope & {
    data: ObservabilityHealthResponse;
};

export interface ObservabilityMetricsLatency {
    /** Median latency in ms */
    p50: number;
    /** 95th-percentile latency in ms */
    p95: number;
}

export type ObservabilityMetricsSummaryHttp = {
    /** @minimum 0 */
    totalRequests: number;
    /** @minimum 0 */
    totalErrors: number;
    /**
     * Fraction of requests that returned 4xx/5xx
     * @minimum 0
     * @maximum 1
     */
    errorRate: number;
    /** @minimum 0 */
    inFlight: number;
    latencyMs: ObservabilityMetricsLatency;
};

export type ObservabilityMetricsSummaryAuth = {
    /** @minimum 0 */
    loginSuccess?: number;
    /** @minimum 0 */
    loginFailure?: number;
    /** @minimum 0 */
    signupSuccess?: number;
};

export type ObservabilityMetricsSummaryBusiness = {
    /** @minimum 0 */
    checkoutSuccess?: number;
    /** @minimum 0 */
    ordersCreated?: number;
};

export type ObservabilityMetricsSummaryDatabase = {
    /** @minimum 0 */
    queriesTotal?: number;
    /** @minimum 0 */
    errorsTotal?: number;
};

export type ObservabilityMetricsSummaryProcess = {
    /** @minimum 0 */
    uptimeSeconds?: number;
    /** @minimum 0 */
    heapUsedMb?: number;
};

export interface ObservabilityMetricsSummary {
    http: ObservabilityMetricsSummaryHttp;
    auth: ObservabilityMetricsSummaryAuth;
    business: ObservabilityMetricsSummaryBusiness;
    database: ObservabilityMetricsSummaryDatabase;
    process: ObservabilityMetricsSummaryProcess;
    timestamp: string;
}

export interface ObservabilityMetricsSummaryResponse {
    success: true;
    data: ObservabilityMetricsSummary;
}

export type ObservabilityMetricsSummaryResponseEnvelope = SuccessEnvelope & {
    data: ObservabilityMetricsSummaryResponse;
};

export type AuditEventItemActorRole =
    (typeof AuditEventItemActorRole)[keyof typeof AuditEventItemActorRole];

export const AuditEventItemActorRole = {
    admin: 'admin',
    user: 'user',
    anonymous: 'anonymous'
} as const;

export type AuditEventItemOutcome =
    (typeof AuditEventItemOutcome)[keyof typeof AuditEventItemOutcome];

export const AuditEventItemOutcome = {
    success: 'success',
    failure: 'failure'
} as const;

export type AuditEventItemLevel = (typeof AuditEventItemLevel)[keyof typeof AuditEventItemLevel];

export const AuditEventItemLevel = {
    info: 'info',
    warn: 'warn'
} as const;

export type AuditEventItemMetadata = { [key: string]: unknown };

export interface AuditEventItem {
    actor_user_id: string;
    actor_role: AuditEventItemActorRole;
    /** Dot-notation action name (e.g. auth.login.succeeded) */
    action: string;
    outcome: AuditEventItemOutcome;
    ip?: string;
    user_agent?: string;
    request_id?: string;
    trace_id?: string;
    target_type?: string;
    target_id?: string;
    metadata?: AuditEventItemMetadata;
    timestamp: string;
    level: AuditEventItemLevel;
}

export type AuditLogsResponseData = {
    items: AuditEventItem[];
    /** @minimum 0 */
    total: number;
};

export interface AuditLogsResponse {
    success: true;
    data: AuditLogsResponseData;
}

export type AuditLogsResponseEnvelope = SuccessEnvelope & {
    data: AuditLogsResponse;
};

export interface LoginRequest {
    email: Email;
    password: Password;
}

export interface SignupRequest {
    email: Email;
    /** @minLength 3 */
    username: string;
    password: Password;
    passwordConfirm: Password;
    imageUrl?: string;
}

export interface SignupRequestMultipart {
    email: Email;
    /** @minLength 3 */
    username: string;
    password: Password;
    passwordConfirm: Password;
    /** Optional user profile image */
    imageUpload?: Blob;
}

export interface PasswordResetRequest {
    email: Email;
}

export interface PasswordResetConfirmRequest {
    /** One-time password reset token (NOT a JWT). */
    token: string;
    password: Password;
    passwordConfirm: Password;
}

export interface AccountDeleteConfirmRequest {
    /** One-time account deletion token (NOT a JWT). */
    token: string;
}

export interface SearchUsersRequest {
    page?: Page;
    pageSize?: PageSize;
    text?: Text;
    id?: Id;
    email?: Email;
    username?: string;
    active?: boolean;
}

export interface CreateUserRequest {
    email: Email;
    username: string;
    password: Password;
    admin?: boolean;
    active?: boolean;
    imageUrl?: string;
}

export interface CreateUserRequestMultipart {
    email: Email;
    username: string;
    password: Password;
    admin?: boolean;
    active?: boolean;
    /** Optional user profile image */
    imageUpload?: Blob;
}

export interface UpdateUserRequest {
    id: Id;
    email?: Email;
    username?: string;
    password?: Password;
    imageUrl?: string;
}

export interface UpdateUserRequestMultipart {
    id: Id;
    email?: Email;
    username?: string;
    password?: Password;
    /** Optional user profile image */
    imageUpload?: Blob;
}

export interface UpdateUserByIdRequest {
    email?: Email;
    password?: Password;
    username?: string;
    imageUrl?: string;
}

export interface UpdateUserByIdRequestMultipart {
    email?: Email;
    password?: Password;
    username?: string;
    /** Optional user profile image */
    imageUpload?: Blob;
}

export interface DeleteUserRequest {
    id: Id;
    hardDelete?: boolean;
}

export interface SearchProductsRequest {
    page?: Page;
    pageSize?: PageSize;
    text?: Text;
    id?: Id;
    /** @minimum 0 */
    minPrice?: number;
    /** @minimum 0 */
    maxPrice?: number;
    category?: string;
    tag?: string;
}

export interface CreateProductRequest {
    title: string;
    /** @minimum 0 */
    price: number;
    description?: string;
    active?: boolean;
    imageUrl?: string;
    categories?: string[];
    tags?: string[];
}

export interface CreateProductRequestMultipart {
    title: string;
    /** @minimum 0 */
    price: number;
    description?: string;
    active?: boolean;
    /** Optional product image */
    imageUpload?: Blob;
    categories?: string[];
    tags?: string[];
}

export interface UpdateProductRequest {
    id: Id;
    title: string;
    description?: string;
    /** @minimum 0 */
    price: number;
    active?: boolean;
    imageUrl?: string;
    categories?: string[];
    tags?: string[];
}

export interface UpdateProductRequestMultipart {
    id: Id;
    title: string;
    description?: string;
    /** @minimum 0 */
    price: number;
    active?: boolean;
    /** Optional product image */
    imageUpload?: Blob;
    categories?: string[];
    tags?: string[];
}

export interface UpdateProductByIdRequest {
    title: string;
    description?: string;
    /** @minimum 0 */
    price: number;
    active?: boolean;
    imageUrl?: string;
    categories?: string[];
    tags?: string[];
}

export interface UpdateProductByIdRequestMultipart {
    title: string;
    description?: string;
    /** @minimum 0 */
    price: number;
    active?: boolean;
    /** Optional product image */
    imageUpload?: Blob;
    categories?: string[];
    tags?: string[];
}

export interface DeleteProductRequest {
    id: Id;
    hardDelete?: boolean;
}

export interface UpsertCartItemRequest {
    productId: Id;
    /** @minimum 1 */
    quantity: number;
}

export interface UpdateCartItemByIdRequest {
    productId?: Id;
    /** @minimum 1 */
    quantity: number;
}

export interface RemoveCartItemRequest {
    productId?: Id;
}

export interface CheckoutRequest {
    email?: Email;
    /** Optional order notes */
    notes?: string;
}

export interface SearchOrdersRequest {
    page?: Page;
    pageSize?: PageSize;
    id?: Id;
    userId?: Id;
    productId?: Id;
    email?: Email;
}

/**
 * Create a new order.
 */
export interface CreateOrderRequest {
    userId: Id;
    email: Email;
    /** @minItems 1 */
    items: CartItem[];
}

/**
 * Updated order status
 */
export type UpdateOrderRequestStatus =
    (typeof UpdateOrderRequestStatus)[keyof typeof UpdateOrderRequestStatus];

export const UpdateOrderRequestStatus = {
    pending: 'pending',
    paid: 'paid',
    processing: 'processing',
    shipped: 'shipped',
    delivered: 'delivered',
    cancelled: 'cancelled'
} as const;

export interface UpdateOrderRequest {
    id: Id;
    /** Updated order status */
    status?: UpdateOrderRequestStatus;
    userId?: Id;
    email?: Email;
    /** @minItems 1 */
    items?: CartItem[];
}

/**
 * Updated order status
 */
export type UpdateOrderByIdRequestStatus =
    (typeof UpdateOrderByIdRequestStatus)[keyof typeof UpdateOrderByIdRequestStatus];

export const UpdateOrderByIdRequestStatus = {
    pending: 'pending',
    paid: 'paid',
    processing: 'processing',
    shipped: 'shipped',
    delivered: 'delivered',
    cancelled: 'cancelled'
} as const;

export interface UpdateOrderByIdRequest {
    /** Updated order status */
    status?: UpdateOrderByIdRequestStatus;
    userId?: Id;
    email?: Email;
    /** @minItems 1 */
    items?: CartItem[];
}

export interface DeleteOrderRequest {
    id: Id;
}

export interface CreateFeedbackRequest {
    name?: string;
    email: Email;
    subject: string;
    message: string;
}

export type SearchFeedbackRequestsRequestStatus =
    (typeof SearchFeedbackRequestsRequestStatus)[keyof typeof SearchFeedbackRequestsRequestStatus];

export const SearchFeedbackRequestsRequestStatus = {
    new: 'new',
    in_progress: 'in_progress',
    resolved: 'resolved',
    spam: 'spam'
} as const;

export interface SearchFeedbackRequestsRequest {
    page?: Page;
    pageSize?: PageSize;
    text?: Text;
    status?: SearchFeedbackRequestsRequestStatus;
    email?: Email;
}

export type UpdateFeedbackRequestStatusRequestStatus =
    (typeof UpdateFeedbackRequestStatusRequestStatus)[keyof typeof UpdateFeedbackRequestStatusRequestStatus];

export const UpdateFeedbackRequestStatusRequestStatus = {
    new: 'new',
    in_progress: 'in_progress',
    resolved: 'resolved',
    spam: 'spam'
} as const;

export interface UpdateFeedbackRequestStatusRequest {
    status?: UpdateFeedbackRequestStatusRequestStatus;
    adminNotes?: string;
}

/**
 * Success
 */
export type SuccessResponse = MessageResponse;

/**
 * Unauthorized
 */
export type UnauthorizedResponse = ErrorResponse;

/**
 * Forbidden
 */
export type ForbiddenResponse = ErrorResponse;

/**
 * Resource not found
 */
export type NotFoundResponse = ErrorResponse;

/**
 * Internal server error
 */
export type InternalErrorResponse = ErrorResponse;

export type PageParamParameter = Page;

export type PageSizeParamParameter = PageSize;

export type TextParamParameter = Text;

export type IdParamParameter = Id;

export type UserIdParamParameter = Id;

export type ProductIdParamParameter = Id;

export type GetObservabilityAuditLogsParams = {
    /**
     * Filter by actor user ID
     */
    actor?: string;
    /**
     * Filter by action name (e.g. auth.login.failed)
     */
    action?: string;
    /**
     * Filter by outcome
     */
    outcome?: GetObservabilityAuditLogsOutcome;
    /**
     * Return events after this ISO-8601 timestamp
     */
    since?: string;
    /**
     * Maximum number of events to return
     * @minimum 1
     * @maximum 200
     */
    limit?: number;
};

export type GetObservabilityAuditLogsOutcome =
    (typeof GetObservabilityAuditLogsOutcome)[keyof typeof GetObservabilityAuditLogsOutcome];

export const GetObservabilityAuditLogsOutcome = {
    success: 'success',
    failure: 'failure'
} as const;

export type ListUsersParams = {
    /**
     * 1-based page index
     * @minimum 1
     */
    page?: PageParamParameter;
    /**
     * Optional override; server may clamp to a max
     * @minimum 1
     * @maximum 100
     */
    pageSize?: PageSizeParamParameter;
    /**
     * Free-text search string
     * @minLength 1
     */
    text?: TextParamParameter;
    /**
     * Resource identifier
     */
    id?: IdParamParameter;
    email?: Email;
    username?: string;
    active?: boolean;
};

export type DeleteUserByIdParams = {
    hardDelete?: boolean;
};

export type ListProductsParams = {
    /**
     * 1-based page index
     * @minimum 1
     */
    page?: PageParamParameter;
    /**
     * Optional override; server may clamp to a max
     * @minimum 1
     * @maximum 100
     */
    pageSize?: PageSizeParamParameter;
    /**
     * Free-text search string
     * @minLength 1
     */
    text?: TextParamParameter;
    /**
     * Resource identifier
     */
    productId?: ProductIdParamParameter;
    /**
     * @minimum 0
     */
    minPrice?: number;
    /**
     * @minimum 0
     */
    maxPrice?: number;
};

export type DeleteProductByIdParams = {
    hardDelete?: boolean;
};

export type ListOrdersParams = {
    /**
     * 1-based page index
     * @minimum 1
     */
    page?: PageParamParameter;
    /**
     * Optional override; server may clamp to a max
     * @minimum 1
     * @maximum 100
     */
    pageSize?: PageSizeParamParameter;
    /**
     * Resource identifier
     */
    id?: IdParamParameter;
    /**
     * Resource identifier
     */
    userId?: UserIdParamParameter;
    /**
     * Resource identifier
     */
    productId?: ProductIdParamParameter;
    email?: Email;
};

/**
 * Public ping endpoint. Returns a simple liveness indicator confirming the API process is running.
 * @summary API health check
 */
export const getHealth = () => {
    return orvalMutator<MessageResponse>({ url: `/`, method: 'GET' });
};

/**
 * Live Server-Sent Events stream for demo dashboards.
 * Sends `metrics.snapshot` on connect, followed by periodic `metrics.updated` and `heartbeat` events.
 * @summary Observability SSE stream
 */
export const getObservabilityEvents = () => {
    return orvalMutator<string>({ url: `/observability/events`, method: 'GET' });
};

/**
 * Full JSON health snapshot for dashboard use.
 * Includes uptime, database status, memory, integrations, and system info.
 * Requires admin role.
 * @summary Health snapshot
 */
export const getObservabilityHealth = () => {
    return orvalMutator<ObservabilityHealthResponseEnvelope>({
        url: `/observability/health`,
        method: 'GET'
    });
};

/**
 * Raw Prometheus text (exposition format 0.0.4).
 * Intended for Prometheus scraping, not for browser clients.
 * Use `GET /observability/metrics/overview` for a JSON summary suitable for dashboards.
 * @summary Prometheus metrics
 */
export const getObservabilityMetrics = () => {
    return orvalMutator<string>({ url: `/observability/metrics`, method: 'GET' });
};

/**
 * Key operational metrics derived from Prometheus counters/histograms,
 * returned as structured JSON for dashboard KPI cards and charts.
 * Requires admin role.
 * @summary Metrics overview (JSON)
 */
export const getObservabilityMetricsOverview = () => {
    return orvalMutator<ObservabilityMetricsSummaryResponseEnvelope>({
        url: `/observability/metrics/overview`,
        method: 'GET'
    });
};

/**
 * Returns the most recent audit events from the in-memory ring buffer (up to 200).
 * Events include auth flows, admin CRUD actions, and security blocks.
 * Requires admin role.
 * @summary Recent audit events
 */
export const getObservabilityAuditLogs = (params?: GetObservabilityAuditLogsParams) => {
    return orvalMutator<AuditLogsResponseEnvelope>({
        url: `/observability/audit`,
        method: 'GET',
        params
    });
};

/**
 * Returns the full profile of the currently authenticated user
 * @summary Current user info
 */
export const getAccount = () => {
    return orvalMutator<UserEnvelope>({ url: `/account`, method: 'GET' });
};

/**
 * Initiates the account-deletion flow for the authenticated user. A one-time confirmation token is sent to the user's email address. The token must then be submitted to `/account/delete-confirm` to complete the deletion.
 * @summary Request account deletion
 */
export const requestAccountDelete = () => {
    return orvalMutator<SuccessResponse>({ url: `/account`, method: 'DELETE' });
};

/**
 * Completes the account-deletion flow. Validates the one-time token issued by `DELETE /account` and, if valid, permanently removes the user account.
 * @summary Confirm account deletion
 */
export const confirmAccountDelete = (accountDeleteConfirmRequest: AccountDeleteConfirmRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/account/delete-confirm`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: accountDeleteConfirmRequest
    });
};

/**
 * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
 * @summary Login
 */
export const login = (loginRequest: LoginRequest) => {
    return orvalMutator<AuthTokensEnvelope>({
        url: `/account/login`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: loginRequest
    });
};

/**
 * Registers a new user account with optional image upload. Returns the newly created user profile on success.
 * @summary Signup
 */
export const signup = (signupBody: SignupRequest | SignupRequestMultipart) => {
    return orvalMutator<UserEnvelope>({ url: `/account/signup`, method: 'POST', data: signupBody });
};

/**
 * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
 */
export const requestPasswordReset = (passwordResetRequest: PasswordResetRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/account/reset`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: passwordResetRequest
    });
};

/**
 * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user's password to the supplied value.
 */
export const confirmPasswordReset = (passwordResetConfirmRequest: PasswordResetConfirmRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/account/reset-confirm`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: passwordResetConfirmRequest
    });
};

/**
 * Creates a new short-lived access token using a refresh token. The refresh token can be provided as a query parameter, path parameter, or retrieved from the `jwt` cookie.
 * @summary Refresh access token
 */
export const refreshToken = () => {
    return orvalMutator<RefreshTokenEnvelope>({ url: `/account/refresh`, method: 'GET' });
};

/**
 * Creates a new short-lived access token using a refresh token provided in the URL path.
 * @summary Refresh access token with token in path
 */
export const refreshTokenWithPath = (token: string) => {
    return orvalMutator<RefreshTokenEnvelope>({ url: `/account/refresh/${token}`, method: 'GET' });
};

/**
 * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
 * @summary Logout from all devices
 */
export const logoutAll = () => {
    return orvalMutator<SuccessResponse>({ url: `/account/logout-all`, method: 'POST' });
};

/**
 * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
 * @summary Remove expired tokens
 */
export const deleteExpiredTokens = () => {
    return orvalMutator<SuccessResponse>({ url: `/account/tokens/expired`, method: 'DELETE' });
};

/**
 * Returns a paginated list of user accounts.
 * @summary List users (paginated)
 */
export const listUsers = (params?: ListUsersParams) => {
    return orvalMutator<UsersResponseEnvelope>({ url: `/users`, method: 'GET', params });
};

/**
 * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
 * @summary Create user
 */
export const createUser = (createUserBody: CreateUserRequest | CreateUserRequestMultipart) => {
    return orvalMutator<UserEnvelope>({ url: `/users`, method: 'POST', data: createUserBody });
};

/**
 * Updates an existing user's email or password. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUser = (updateUserBody: UpdateUserRequest | UpdateUserRequestMultipart) => {
    return orvalMutator<UserEnvelope>({ url: `/users`, method: 'PUT', data: updateUserBody });
};

/**
 * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
 * @summary Delete user
 */
export const deleteUser = (deleteUserRequest: DeleteUserRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/users`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: deleteUserRequest
    });
};

/**
 * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
 * @summary User details
 */
export const getUserById = (id: string) => {
    return orvalMutator<UserEnvelope>({ url: `/users/${id}`, method: 'GET' });
};

/**
 * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUserById = (
    id: string,
    updateUserByIdBody: UpdateUserByIdRequest | UpdateUserByIdRequestMultipart
) => {
    return orvalMutator<UserEnvelope>({
        url: `/users/${id}`,
        method: 'PUT',
        data: updateUserByIdBody
    });
};

/**
 * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
 * @summary Delete user
 */
export const deleteUserById = (id: string, params?: DeleteUserByIdParams) => {
    return orvalMutator<SuccessResponse>({ url: `/users/${id}`, method: 'DELETE', params });
};

/**
 * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
 * @summary Search users (DTO-friendly)
 */
export const searchUsers = (searchUsersRequest: SearchUsersRequest) => {
    return orvalMutator<UsersResponseEnvelope>({
        url: `/users/search`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: searchUsersRequest
    });
};

/**
 * Creates a user feedback/contact request and notifies admins via email.
 * @summary Submit contact request
 */
export const createFeedbackRequest = (createFeedbackRequest: CreateFeedbackRequest) => {
    return orvalMutator<FeedbackRequestEnvelope>({
        url: `/feedback/contact`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createFeedbackRequest
    });
};

/**
 * Returns feedback/contact requests for admin review.
 * @summary List feedback requests
 */
export const listFeedbackRequests = (
    searchFeedbackRequestsRequest?: SearchFeedbackRequestsRequest
) => {
    return orvalMutator<FeedbackRequestsResponseEnvelope>({
        url: `/feedback`,
        method: 'GET',
        headers: { 'Content-Type': 'application/json' }
    });
};

/**
 * Updates status/notes of a feedback request.
 * @summary Update feedback request status
 */
export const updateFeedbackRequestStatus = (
    id: string,
    updateFeedbackRequestStatusRequest: UpdateFeedbackRequestStatusRequest
) => {
    return orvalMutator<FeedbackRequestEnvelope>({
        url: `/feedback/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateFeedbackRequestStatusRequest
    });
};

/**
 * Returns a paginated list of products.
 * @summary List products (paginated)
 */
export const listProducts = (params?: ListProductsParams) => {
    return orvalMutator<ProductsResponseEnvelope>({ url: `/products`, method: 'GET', params });
};

/**
 * Creates a new product with optional image upload
 * @summary Create product
 */
export const createProduct = (
    createProductBody: CreateProductRequest | CreateProductRequestMultipart
) => {
    return orvalMutator<ProductEnvelope>({
        url: `/products`,
        method: 'POST',
        data: createProductBody
    });
};

/**
 * Updates an existing product with optional image upload
 * @summary Edit product
 */
export const updateProduct = (
    updateProductBody: UpdateProductRequest | UpdateProductRequestMultipart
) => {
    return orvalMutator<ProductEnvelope>({
        url: `/products`,
        method: 'PUT',
        data: updateProductBody
    });
};

/**
 * Deletes the product identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record
 * @summary Delete product
 */
export const deleteProduct = (deleteProductRequest: DeleteProductRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/products`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: deleteProductRequest
    });
};

/**
 * Returns the full details of the product identified by `{id}`. Functionally equivalent to `GET /products?id={id}`.
 * @summary Product details
 */
export const getProductById = (id: string) => {
    return orvalMutator<ProductEnvelope>({ url: `/products/${id}`, method: 'GET' });
};

/**
 * Updates the product identified by `{id}` in the path with optional image upload. Functionally equivalent to `PUT /products` with the id in the body.
 * @summary Edit product
 */
export const updateProductById = (
    id: string,
    updateProductByIdBody: UpdateProductByIdRequest | UpdateProductByIdRequestMultipart
) => {
    return orvalMutator<ProductEnvelope>({
        url: `/products/${id}`,
        method: 'PUT',
        data: updateProductByIdBody
    });
};

/**
 * Deletes the product identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /products`.
 * @summary Delete product
 */
export const deleteProductById = (id: string, params?: DeleteProductByIdParams) => {
    return orvalMutator<SuccessResponse>({ url: `/products/${id}`, method: 'DELETE', params });
};

/**
 * Searches and filters products via a JSON request body. Functionally equivalent to `GET /products` with query parameters.
 * @summary Search products (DTO-friendly)
 */
export const searchProducts = (searchProductsRequest: SearchProductsRequest) => {
    return orvalMutator<ProductsResponseEnvelope>({
        url: `/products/search`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: searchProductsRequest
    });
};

/**
 * Returns all items currently in the authenticated user's cart along with a computed summary
 * @summary Get cart
 */
export const getCart = () => {
    return orvalMutator<CartResponseEnvelope>({ url: `/cart`, method: 'GET' });
};

/**
 * Adds or edit a product to the authenticated user's cart. Returns the updated cart.
 * @summary Add/Edit cart item
 */
export const upsertCartItem = (upsertCartItemRequest: UpsertCartItemRequest) => {
    return orvalMutator<CartResponseEnvelope>({
        url: `/cart`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: upsertCartItemRequest
    });
};

/**
 * Clear cart or, ir productId is set, removes a specific product from the authenticated user's cart. Returns the updated cart (can be empty)
 * @summary Empty cart or, if productId is set, remove target cart item
 */
export const clearCart = (removeCartItemRequest?: RemoveCartItemRequest) => {
    return orvalMutator<CartResponseEnvelope>({
        url: `/cart`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: removeCartItemRequest
    });
};

/**
 * Sets the quantity of the cart line for the product identified by `{productId}` in the path. Functionally equivalent to `POST /cart`. Returns the updated cart.
 * @summary Set cart item quantity
 */
export const updateCartItemById = (
    productId: string,
    updateCartItemByIdRequest: UpdateCartItemByIdRequest
) => {
    return orvalMutator<CartResponseEnvelope>({
        url: `/cart/${productId}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateCartItemByIdRequest
    });
};

/**
 * Removes the cart line for the product identified by `{productId}` in the path from the authenticated user's cart. Returns the updated cart.
 * @summary Remove item from cart
 */
export const removeCartItem = (productId: string) => {
    return orvalMutator<CartResponseEnvelope>({ url: `/cart/${productId}`, method: 'DELETE' });
};

/**
 * Returns a lightweight summary of the authenticated user's cart.
 * @summary Get cart summary
 */
export const getCartSummary = () => {
    return orvalMutator<CartSummaryResponseEnvelope>({ url: `/cart/summary`, method: 'GET' });
};

/**
 * Converts the authenticated user's current cart into a new order. The cart is cleared upon success. An optional email address and order notes can be supplied in the request body. Returns the created order.
 * @summary Checkout (place order from cart)
 */
export const checkout = (checkoutRequest?: CheckoutRequest) => {
    return orvalMutator<CheckoutResponseEnvelope>({
        url: `/cart/checkout`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: checkoutRequest
    });
};

/**
 * Returns a paginated list of orders.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary List orders (paginated)
 */
export const listOrders = (params?: ListOrdersParams) => {
    return orvalMutator<OrdersResponseEnvelope>({ url: `/orders`, method: 'GET', params });
};

/**
 * Creates a new order directly from the supplied payload.
 * @summary Create order
 */
export const createOrder = (createOrderRequest: CreateOrderRequest) => {
    return orvalMutator<OrderEnvelope>({
        url: `/orders`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: createOrderRequest
    });
};

/**
 * Updates an existing order identified by id in the request body.
 * @summary Update order
 */
export const updateOrder = (updateOrderRequest: UpdateOrderRequest) => {
    return orvalMutator<OrderEnvelope>({
        url: `/orders`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateOrderRequest
    });
};

/**
 * Permanently removes the order identified by id.
 * @summary Delete order
 */
export const deleteOrder = (deleteOrderRequest: DeleteOrderRequest) => {
    return orvalMutator<SuccessResponse>({
        url: `/orders`,
        method: 'DELETE',
        headers: { 'Content-Type': 'application/json' },
        data: deleteOrderRequest
    });
};

/**
 * Searches and filters orders via a JSON request body. Functionally equivalent to `GET /orders`.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary Search orders (DTO-friendly)
 */
export const searchOrders = (searchOrdersRequest: SearchOrdersRequest) => {
    return orvalMutator<OrdersResponseEnvelope>({
        url: `/orders/search`,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        data: searchOrdersRequest
    });
};

/**
 * Returns the full details of the order identified by `{id}`. Functionally equivalent to `GET /orders?id={id}`.
 * @summary Order details
 */
export const getOrderById = (id: string) => {
    return orvalMutator<OrderEnvelope>({ url: `/orders/${id}`, method: 'GET' });
};

/**
 * Updates the order identified by `{id}` in the path.
 * @summary Edit order
 */
export const updateOrderById = (id: string, updateOrderByIdRequest: UpdateOrderByIdRequest) => {
    return orvalMutator<OrderEnvelope>({
        url: `/orders/${id}`,
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        data: updateOrderByIdRequest
    });
};

/**
 * Permanently removes the order identified by `id`.
 * @summary Delete order
 */
export const deleteOrderById = (id: string) => {
    return orvalMutator<SuccessResponse>({ url: `/orders/${id}`, method: 'DELETE' });
};

/**
 * Generates and returns the invoice for the order identified by `{id}` as a binary PDF file. The client should save or stream the response with an appropriate `Content-Disposition` header.
 * @summary Download order invoice (PDF)
 */
export const getOrderInvoice = (id: string) => {
    return orvalMutator<Blob>({
        url: `/orders/${id}/invoice`,
        method: 'GET',
        responseType: 'blob'
    });
};

export type GetHealthResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>;
export type GetObservabilityEventsResult = NonNullable<
    Awaited<ReturnType<typeof getObservabilityEvents>>
>;
export type GetObservabilityHealthResult = NonNullable<
    Awaited<ReturnType<typeof getObservabilityHealth>>
>;
export type GetObservabilityMetricsResult = NonNullable<
    Awaited<ReturnType<typeof getObservabilityMetrics>>
>;
export type GetObservabilityMetricsOverviewResult = NonNullable<
    Awaited<ReturnType<typeof getObservabilityMetricsOverview>>
>;
export type GetObservabilityAuditLogsResult = NonNullable<
    Awaited<ReturnType<typeof getObservabilityAuditLogs>>
>;
export type GetAccountResult = NonNullable<Awaited<ReturnType<typeof getAccount>>>;
export type RequestAccountDeleteResult = NonNullable<
    Awaited<ReturnType<typeof requestAccountDelete>>
>;
export type ConfirmAccountDeleteResult = NonNullable<
    Awaited<ReturnType<typeof confirmAccountDelete>>
>;
export type LoginResult = NonNullable<Awaited<ReturnType<typeof login>>>;
export type SignupResult = NonNullable<Awaited<ReturnType<typeof signup>>>;
export type RequestPasswordResetResult = NonNullable<
    Awaited<ReturnType<typeof requestPasswordReset>>
>;
export type ConfirmPasswordResetResult = NonNullable<
    Awaited<ReturnType<typeof confirmPasswordReset>>
>;
export type RefreshTokenResult = NonNullable<Awaited<ReturnType<typeof refreshToken>>>;
export type RefreshTokenWithPathResult = NonNullable<
    Awaited<ReturnType<typeof refreshTokenWithPath>>
>;
export type LogoutAllResult = NonNullable<Awaited<ReturnType<typeof logoutAll>>>;
export type DeleteExpiredTokensResult = NonNullable<
    Awaited<ReturnType<typeof deleteExpiredTokens>>
>;
export type ListUsersResult = NonNullable<Awaited<ReturnType<typeof listUsers>>>;
export type CreateUserResult = NonNullable<Awaited<ReturnType<typeof createUser>>>;
export type UpdateUserResult = NonNullable<Awaited<ReturnType<typeof updateUser>>>;
export type DeleteUserResult = NonNullable<Awaited<ReturnType<typeof deleteUser>>>;
export type GetUserByIdResult = NonNullable<Awaited<ReturnType<typeof getUserById>>>;
export type UpdateUserByIdResult = NonNullable<Awaited<ReturnType<typeof updateUserById>>>;
export type DeleteUserByIdResult = NonNullable<Awaited<ReturnType<typeof deleteUserById>>>;
export type SearchUsersResult = NonNullable<Awaited<ReturnType<typeof searchUsers>>>;
export type CreateFeedbackRequestResult = NonNullable<
    Awaited<ReturnType<typeof createFeedbackRequest>>
>;
export type ListFeedbackRequestsResult = NonNullable<
    Awaited<ReturnType<typeof listFeedbackRequests>>
>;
export type UpdateFeedbackRequestStatusResult = NonNullable<
    Awaited<ReturnType<typeof updateFeedbackRequestStatus>>
>;
export type ListProductsResult = NonNullable<Awaited<ReturnType<typeof listProducts>>>;
export type CreateProductResult = NonNullable<Awaited<ReturnType<typeof createProduct>>>;
export type UpdateProductResult = NonNullable<Awaited<ReturnType<typeof updateProduct>>>;
export type DeleteProductResult = NonNullable<Awaited<ReturnType<typeof deleteProduct>>>;
export type GetProductByIdResult = NonNullable<Awaited<ReturnType<typeof getProductById>>>;
export type UpdateProductByIdResult = NonNullable<Awaited<ReturnType<typeof updateProductById>>>;
export type DeleteProductByIdResult = NonNullable<Awaited<ReturnType<typeof deleteProductById>>>;
export type SearchProductsResult = NonNullable<Awaited<ReturnType<typeof searchProducts>>>;
export type GetCartResult = NonNullable<Awaited<ReturnType<typeof getCart>>>;
export type UpsertCartItemResult = NonNullable<Awaited<ReturnType<typeof upsertCartItem>>>;
export type ClearCartResult = NonNullable<Awaited<ReturnType<typeof clearCart>>>;
export type UpdateCartItemByIdResult = NonNullable<Awaited<ReturnType<typeof updateCartItemById>>>;
export type RemoveCartItemResult = NonNullable<Awaited<ReturnType<typeof removeCartItem>>>;
export type GetCartSummaryResult = NonNullable<Awaited<ReturnType<typeof getCartSummary>>>;
export type CheckoutResult = NonNullable<Awaited<ReturnType<typeof checkout>>>;
export type ListOrdersResult = NonNullable<Awaited<ReturnType<typeof listOrders>>>;
export type CreateOrderResult = NonNullable<Awaited<ReturnType<typeof createOrder>>>;
export type UpdateOrderResult = NonNullable<Awaited<ReturnType<typeof updateOrder>>>;
export type DeleteOrderResult = NonNullable<Awaited<ReturnType<typeof deleteOrder>>>;
export type SearchOrdersResult = NonNullable<Awaited<ReturnType<typeof searchOrders>>>;
export type GetOrderByIdResult = NonNullable<Awaited<ReturnType<typeof getOrderById>>>;
export type UpdateOrderByIdResult = NonNullable<Awaited<ReturnType<typeof updateOrderById>>>;
export type DeleteOrderByIdResult = NonNullable<Awaited<ReturnType<typeof deleteOrderById>>>;
export type GetOrderInvoiceResult = NonNullable<Awaited<ReturnType<typeof getOrderInvoice>>>;
