/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * Ecommerce Demo API
 * Stable, codegen-oriented OpenAPI contract.
 * Designed for multi-project, multi-language use (client/server stubs, DTOs, SDKs).
 *
 * OpenAPI spec version: 2.0.0
 */
import * as zod from 'zod';

/**
 * Public ping endpoint. Returns a simple liveness indicator confirming the API process is running.
 * @summary API health check
 */
export const GetHealthResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        status: zod
            .enum(['ok'])
            .describe('Liveness indicator. Always `ok` when the process is answering.')
    })
});

/**
 * Live Server-Sent Events stream for demo dashboards.
 * Sends `metrics.snapshot` on connect, followed by periodic `metrics.updated` and `heartbeat` events.
 * @summary Observability SSE stream
 */
export const GetObservabilityEventsResponse = zod.unknown();

/**
 * Full JSON health snapshot for dashboard use.
 * Includes uptime, database status, memory, integrations, and system info.
 * Requires admin role.
 * @summary Health snapshot
 */
export const getObservabilityHealthResponseDataDataUptimeSecondsMin = 0;

export const GetObservabilityHealthResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        success: zod.literal(true),
        data: zod.strictObject({
            status: zod.enum(['ok', 'degraded']),
            environment: zod.string(),
            service: zod.string(),
            nodeVersion: zod.string(),
            uptimeSeconds: zod.number().min(getObservabilityHealthResponseDataDataUptimeSecondsMin),
            database: zod.strictObject({
                status: zod.enum(['connected', 'connecting', 'disconnected'])
            }),
            integrations: zod
                .strictObject({
                    loki: zod.boolean().optional(),
                    posthog: zod.boolean().optional(),
                    otelEnabled: zod.boolean().optional(),
                    umami: zod.boolean().optional(),
                    faro: zod.boolean().optional()
                })
                .optional(),
            memory: zod
                .strictObject({
                    heapUsedMb: zod.number(),
                    heapTotalMb: zod.number(),
                    rssMb: zod.number()
                })
                .optional(),
            system: zod
                .strictObject({
                    platform: zod.string(),
                    cpuCount: zod.number(),
                    loadAvg: zod.array(zod.number())
                })
                .optional(),
            timestamp: zod.iso.datetime({ offset: true })
        })
    })
});

/**
 * Raw Prometheus text (exposition format 0.0.4).
 * Intended for Prometheus scraping, not for browser clients.
 * Use `GET /observability/metrics/overview` for a JSON summary suitable for dashboards.
 * @summary Prometheus metrics
 */
export const GetObservabilityMetricsResponse = zod.string();

/**
 * Key operational metrics derived from Prometheus counters/histograms,
 * returned as structured JSON for dashboard KPI cards and charts.
 * Requires admin role.
 * @summary Metrics overview (JSON)
 */
export const getObservabilityMetricsOverviewResponseDataDataHttpTotalRequestsMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataHttpTotalErrorsMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataHttpErrorRateMin = 0;
export const getObservabilityMetricsOverviewResponseDataDataHttpErrorRateMax = 1;

export const getObservabilityMetricsOverviewResponseDataDataHttpInFlightMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataAuthLoginSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataAuthLoginFailureMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataAuthSignupSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataBusinessCheckoutSuccessMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataBusinessOrdersCreatedMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataDatabaseQueriesTotalMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataDatabaseErrorsTotalMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataProcessUptimeSecondsMin = 0;

export const getObservabilityMetricsOverviewResponseDataDataProcessHeapUsedMbMin = 0;

export const GetObservabilityMetricsOverviewResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        success: zod.literal(true),
        data: zod.strictObject({
            http: zod.strictObject({
                totalRequests: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataHttpTotalRequestsMin),
                totalErrors: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataHttpTotalErrorsMin),
                errorRate: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataHttpErrorRateMin)
                    .max(getObservabilityMetricsOverviewResponseDataDataHttpErrorRateMax)
                    .describe('Fraction of requests that returned 4xx\/5xx'),
                inFlight: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataHttpInFlightMin),
                latencyMs: zod.strictObject({
                    p50: zod.number().describe('Median latency in ms'),
                    p95: zod.number().describe('95th-percentile latency in ms')
                })
            }),
            auth: zod.strictObject({
                loginSuccess: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataAuthLoginSuccessMin)
                    .optional(),
                loginFailure: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataAuthLoginFailureMin)
                    .optional(),
                signupSuccess: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataAuthSignupSuccessMin)
                    .optional()
            }),
            business: zod.strictObject({
                checkoutSuccess: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataBusinessCheckoutSuccessMin)
                    .optional(),
                ordersCreated: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataBusinessOrdersCreatedMin)
                    .optional()
            }),
            database: zod.strictObject({
                queriesTotal: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataDatabaseQueriesTotalMin)
                    .optional(),
                errorsTotal: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataDatabaseErrorsTotalMin)
                    .optional()
            }),
            process: zod.strictObject({
                uptimeSeconds: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataProcessUptimeSecondsMin)
                    .optional(),
                heapUsedMb: zod
                    .number()
                    .min(getObservabilityMetricsOverviewResponseDataDataProcessHeapUsedMbMin)
                    .optional()
            }),
            timestamp: zod.iso.datetime({ offset: true })
        })
    })
});

/**
 * Returns the most recent audit events from the in-memory ring buffer (up to 200).
 * Events include auth flows, admin CRUD actions, and security blocks.
 * Requires admin role.
 * @summary Recent audit events
 */
export const getObservabilityAuditLogsQueryLimitDefault = 50;
export const getObservabilityAuditLogsQueryLimitMax = 200;

export const GetObservabilityAuditLogsQueryParams = zod.strictObject({
    actor: zod.string().optional().describe('Filter by actor user ID'),
    action: zod.string().optional().describe('Filter by action name (e.g. auth.login.failed)'),
    outcome: zod.enum(['success', 'failure']).optional().describe('Filter by outcome'),
    since: zod.iso
        .datetime({ offset: true })
        .optional()
        .describe('Return events after this ISO-8601 timestamp'),
    limit: zod
        .number()
        .min(1)
        .max(getObservabilityAuditLogsQueryLimitMax)
        .default(getObservabilityAuditLogsQueryLimitDefault)
        .describe('Maximum number of events to return')
});

export const getObservabilityAuditLogsResponseDataDataTotalMin = 0;

export const GetObservabilityAuditLogsResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        success: zod.literal(true),
        data: zod.strictObject({
            items: zod.array(
                zod.strictObject({
                    actor_user_id: zod.string(),
                    actor_role: zod.enum(['admin', 'user', 'anonymous']),
                    action: zod
                        .string()
                        .describe('Dot-notation action name (e.g. auth.login.succeeded)'),
                    outcome: zod.enum(['success', 'failure']),
                    ip: zod.string().optional(),
                    user_agent: zod.string().optional(),
                    request_id: zod.string().optional(),
                    trace_id: zod.string().optional(),
                    target_type: zod.string().optional(),
                    target_id: zod.string().optional(),
                    metadata: zod.record(zod.string(), zod.unknown()).optional(),
                    timestamp: zod.iso.datetime({ offset: true }),
                    level: zod.enum(['info', 'warn'])
                })
            ),
            total: zod.number().min(getObservabilityAuditLogsResponseDataDataTotalMin)
        })
    })
});

/**
 * Dev/staging-only endpoint that busy-loops the event loop for a fixed amount of
 * work while emitting log lines, so dashboards and log pipelines can be exercised
 * under load. Not registered when `NODE_ENV=production`. Requires admin role.
 * @summary Synthetic CPU load test
 */
export const GetObservabilityLoadTestResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        durationMs: zod.number().describe('Wall-clock time in ms spent on the synthetic CPU load')
    })
});

/**
 * Returns the full profile of the currently authenticated user
 * @summary Current user info
 */
export const GetAccountResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Initiates the account-deletion flow for the authenticated user. A one-time confirmation token is sent to the user's email address. The token must then be submitted to `/account/delete-confirm` to complete the deletion.
 * @summary Request account deletion
 */
export const RequestAccountDeleteResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Completes the account-deletion flow. Validates the one-time token issued by `DELETE /account` and, if valid, permanently removes the user account.
 * @summary Confirm account deletion
 */
export const ConfirmAccountDeleteBody = zod.strictObject({
    token: zod.string().describe('One-time account deletion token (NOT a JWT).')
});

export const ConfirmAccountDeleteResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Authenticates a user with email and password credentials. On success, returns a JWT access token that must be passed as a Bearer token on subsequent authenticated requests.
 * @summary Login
 */
export const loginBodyPasswordMin = 8;

export const LoginBody = zod.strictObject({
    email: zod.email(),
    password: zod.string().min(loginBodyPasswordMin)
});

export const LoginResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        token: zod.string().describe('Access JWT'),
        refreshToken: zod.string().optional().describe('Refresh token if returned by backend'),
        expiresIn: zod.number().optional().describe('Access token expiry in seconds')
    })
});

/**
 * Registers a new user account with optional image upload. Returns the newly created user profile on success.
 * @summary Signup
 */
export const signupBodyUsernameMin = 3;

export const signupBodyPasswordMin = 8;

export const signupBodyPasswordConfirmMin = 8;

export const SignupBody = zod.strictObject({
    email: zod.email(),
    username: zod.string().min(signupBodyUsernameMin),
    password: zod.string().min(signupBodyPasswordMin),
    passwordConfirm: zod.string().min(signupBodyPasswordConfirmMin),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        )
});

export const SignupResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Initiates the password-reset flow by sending a one-time reset token to the provided email address. The token should then be submitted to `/account/reset-confirm`.
 */
export const RequestPasswordResetBody = zod.strictObject({
    email: zod.email()
});

export const RequestPasswordResetResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Completes the password-reset flow. Validates the one-time reset token issued by `/account/reset` and, if valid, updates the user's password to the supplied value.
 */
export const confirmPasswordResetBodyPasswordMin = 8;

export const confirmPasswordResetBodyPasswordConfirmMin = 8;

export const ConfirmPasswordResetBody = zod.strictObject({
    token: zod.string().describe('One-time password reset token (NOT a JWT).'),
    password: zod.string().min(confirmPasswordResetBodyPasswordMin),
    passwordConfirm: zod.string().min(confirmPasswordResetBodyPasswordConfirmMin)
});

export const ConfirmPasswordResetResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Creates a new short-lived access token from the refresh token in the `jwt` cookie. The cookie is `HttpOnly`, so the token is never readable by page scripts and never appears in a URL, a proxy log or a `Referer` header.
 * @summary Refresh access token
 */
export const RefreshTokenResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        token: zod.string().describe('New access JWT'),
        refreshToken: zod.string().optional().describe('New refresh token if returned by backend'),
        expiresIn: zod.number().optional().describe('New access token expiry in seconds')
    })
});

/**
 * Logs out the authenticated user from ALL devices by removing all refresh tokens from the database and clearing authentication cookies.
 * @summary Logout from all devices
 */
export const LogoutAllResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Removes all expired tokens (refresh, password-reset, etc.) from every user record in the database. Restricted to administrators.
 * @summary Remove expired tokens
 */
export const DeleteExpiredTokensResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Returns a paginated list of user accounts.
 * @summary List users (paginated)
 */
export const listUsersQueryPageDefault = 1;

export const listUsersQueryPageSizeDefault = 10;
export const listUsersQueryPageSizeMax = 100;

export const ListUsersQueryParams = zod.strictObject({
    page: zod.number().min(1).default(listUsersQueryPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(listUsersQueryPageSizeMax)
        .default(listUsersQueryPageSizeDefault),
    text: zod.string().min(1).optional(),
    id: zod.string().optional(),
    email: zod.email().optional(),
    username: zod.string().optional(),
    active: zod.boolean().optional()
});

export const listUsersResponseDataMetaPageDefault = 1;

export const listUsersResponseDataMetaPageSizeDefault = 10;
export const listUsersResponseDataMetaPageSizeMax = 100;

export const listUsersResponseDataMetaTotalItemsMin = 0;

export const listUsersResponseDataMetaTotalPagesMin = 0;

export const ListUsersResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                email: zod.email(),
                username: zod.string(),
                admin: zod.boolean().optional(),
                active: zod.boolean().optional(),
                imageUrl: zod
                    .string()
                    .optional()
                    .describe(
                        'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                    ),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(listUsersResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(listUsersResponseDataMetaPageSizeMax)
                .default(listUsersResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(listUsersResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(listUsersResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Creates a new user account with the supplied email, username, and password. Optional image can be uploaded.
 * @summary Create user
 */
export const createUserBodyPasswordMin = 8;

export const CreateUserBody = zod.strictObject({
    email: zod.email(),
    username: zod.string(),
    password: zod.string().min(createUserBodyPasswordMin),
    admin: zod.boolean().optional(),
    active: zod.boolean().optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        )
});

export const CreateUserResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates an existing user's email or password. Optional image can be uploaded.
 * @summary Edit user
 */
export const updateUserBodyPasswordMin = 8;

export const UpdateUserBody = zod.strictObject({
    id: zod.string().describe('Resource identifier'),
    email: zod.email().optional(),
    username: zod.string().optional(),
    password: zod.string().min(updateUserBodyPasswordMin).optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        )
});

export const UpdateUserResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Deletes the user identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record.
 * @summary Delete user
 */
export const deleteUserBodyHardDeleteDefault = false;

export const DeleteUserBody = zod.strictObject({
    id: zod.string().describe('Resource identifier'),
    hardDelete: zod.boolean().default(deleteUserBodyHardDeleteDefault)
});

export const DeleteUserResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Returns the full profile of the user identified by `{id}`. Functionally equivalent to `GET /users?id={id}`.
 * @summary User details
 */
export const GetUserByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const GetUserByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates the email or password of the user identified by `{id}` in the path. Optional image can be uploaded.
 * @summary Edit user
 */
export const UpdateUserByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const updateUserByIdBodyPasswordMin = 8;

export const UpdateUserByIdBody = zod.strictObject({
    email: zod.email().optional(),
    password: zod.string().min(updateUserByIdBodyPasswordMin).optional(),
    username: zod.string().optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        )
});

export const UpdateUserByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        email: zod.email(),
        username: zod.string(),
        admin: zod.boolean().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Deletes the user identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /users`.
 * @summary Delete user
 */
export const DeleteUserByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const DeleteUserByIdQueryParams = zod.strictObject({
    hardDelete: zod.boolean().optional()
});

export const DeleteUserByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Searches and filters users via a JSON request body. Functionally equivalent to `GET /users` with query parameters
 * @summary Search users (DTO-friendly)
 */
export const searchUsersBodyPageDefault = 1;

export const searchUsersBodyPageSizeDefault = 10;
export const searchUsersBodyPageSizeMax = 100;

export const SearchUsersBody = zod.strictObject({
    page: zod.number().min(1).default(searchUsersBodyPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(searchUsersBodyPageSizeMax)
        .default(searchUsersBodyPageSizeDefault)
        .describe('Optional override; server may clamp to a max'),
    text: zod.string().min(1).optional().describe('Free-text search string'),
    id: zod.string().optional().describe('Resource identifier'),
    email: zod.email().optional(),
    username: zod.string().optional(),
    active: zod.boolean().optional()
});

export const searchUsersResponseDataMetaPageDefault = 1;

export const searchUsersResponseDataMetaPageSizeDefault = 10;
export const searchUsersResponseDataMetaPageSizeMax = 100;

export const searchUsersResponseDataMetaTotalItemsMin = 0;

export const searchUsersResponseDataMetaTotalPagesMin = 0;

export const SearchUsersResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                email: zod.email(),
                username: zod.string(),
                admin: zod.boolean().optional(),
                active: zod.boolean().optional(),
                imageUrl: zod
                    .string()
                    .optional()
                    .describe(
                        'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                    ),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(searchUsersResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(searchUsersResponseDataMetaPageSizeMax)
                .default(searchUsersResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(searchUsersResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(searchUsersResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Creates a user feedback/contact request and notifies admins via email.
 * @summary Submit contact request
 */
export const CreateFeedbackRequestBody = zod.strictObject({
    name: zod.string().optional(),
    email: zod.email(),
    subject: zod.string(),
    message: zod.string()
});

export const CreateFeedbackRequestResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        name: zod.string().optional(),
        email: zod.email(),
        subject: zod.string(),
        message: zod.string(),
        status: zod.enum(['new', 'in_progress', 'resolved', 'spam']),
        adminNotes: zod.string().optional(),
        respondedAt: zod.iso.datetime({ offset: true }).optional(),
        createdAt: zod.iso.datetime({ offset: true }),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Returns feedback/contact requests for admin review.
 * @summary List feedback requests
 */
export const listFeedbackRequestsBodyPageDefault = 1;

export const listFeedbackRequestsBodyPageSizeDefault = 10;
export const listFeedbackRequestsBodyPageSizeMax = 100;

export const ListFeedbackRequestsBody = zod.strictObject({
    page: zod
        .number()
        .min(1)
        .default(listFeedbackRequestsBodyPageDefault)
        .describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(listFeedbackRequestsBodyPageSizeMax)
        .default(listFeedbackRequestsBodyPageSizeDefault)
        .describe('Optional override; server may clamp to a max'),
    text: zod.string().min(1).optional().describe('Free-text search string'),
    status: zod.enum(['new', 'in_progress', 'resolved', 'spam']).optional(),
    email: zod.email().optional()
});

export const listFeedbackRequestsResponseDataMetaPageDefault = 1;

export const listFeedbackRequestsResponseDataMetaPageSizeDefault = 10;
export const listFeedbackRequestsResponseDataMetaPageSizeMax = 100;

export const listFeedbackRequestsResponseDataMetaTotalItemsMin = 0;

export const listFeedbackRequestsResponseDataMetaTotalPagesMin = 0;

export const ListFeedbackRequestsResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                name: zod.string().optional(),
                email: zod.email(),
                subject: zod.string(),
                message: zod.string(),
                status: zod.enum(['new', 'in_progress', 'resolved', 'spam']),
                adminNotes: zod.string().optional(),
                respondedAt: zod.iso.datetime({ offset: true }).optional(),
                createdAt: zod.iso.datetime({ offset: true }),
                updatedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(listFeedbackRequestsResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(listFeedbackRequestsResponseDataMetaPageSizeMax)
                .default(listFeedbackRequestsResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(listFeedbackRequestsResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(listFeedbackRequestsResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Updates status/notes of a feedback request.
 * @summary Update feedback request status
 */
export const UpdateFeedbackRequestStatusParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const UpdateFeedbackRequestStatusBody = zod.strictObject({
    status: zod.enum(['new', 'in_progress', 'resolved', 'spam']).optional(),
    adminNotes: zod.string().optional()
});

export const UpdateFeedbackRequestStatusResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        name: zod.string().optional(),
        email: zod.email(),
        subject: zod.string(),
        message: zod.string(),
        status: zod.enum(['new', 'in_progress', 'resolved', 'spam']),
        adminNotes: zod.string().optional(),
        respondedAt: zod.iso.datetime({ offset: true }).optional(),
        createdAt: zod.iso.datetime({ offset: true }),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Returns a paginated list of products.
 * @summary List products (paginated)
 */
export const listProductsQueryPageDefault = 1;

export const listProductsQueryPageSizeDefault = 10;
export const listProductsQueryPageSizeMax = 100;

export const listProductsQueryMinPriceMin = 0;

export const listProductsQueryMaxPriceMin = 0;

export const ListProductsQueryParams = zod.strictObject({
    page: zod.number().min(1).default(listProductsQueryPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(listProductsQueryPageSizeMax)
        .default(listProductsQueryPageSizeDefault),
    text: zod.string().min(1).optional(),
    productId: zod.string().optional(),
    minPrice: zod.number().min(listProductsQueryMinPriceMin).optional(),
    maxPrice: zod.number().min(listProductsQueryMaxPriceMin).optional()
});

export const listProductsResponseDataItemsItemPriceMin = 0;

export const listProductsResponseDataMetaPageDefault = 1;

export const listProductsResponseDataMetaPageSizeDefault = 10;
export const listProductsResponseDataMetaPageSizeMax = 100;

export const listProductsResponseDataMetaTotalItemsMin = 0;

export const listProductsResponseDataMetaTotalPagesMin = 0;

export const ListProductsResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                title: zod.string(),
                price: zod.number().min(listProductsResponseDataItemsItemPriceMin),
                description: zod.string().optional(),
                active: zod.boolean().optional(),
                imageUrl: zod
                    .string()
                    .optional()
                    .describe(
                        'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                    ),
                categories: zod.array(zod.string()).optional(),
                tags: zod.array(zod.string()).optional(),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional(),
                deletedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(listProductsResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(listProductsResponseDataMetaPageSizeMax)
                .default(listProductsResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(listProductsResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(listProductsResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Creates a new product with optional image upload
 * @summary Create product
 */
export const createProductBodyPriceMin = 0;

export const CreateProductBody = zod.strictObject({
    title: zod.string(),
    price: zod.number().min(createProductBodyPriceMin),
    description: zod.string().optional(),
    active: zod.boolean().optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        ),
    categories: zod.array(zod.string()).optional(),
    tags: zod.array(zod.string()).optional()
});

export const createProductResponseDataPriceMin = 0;

export const CreateProductResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        title: zod.string(),
        price: zod.number().min(createProductResponseDataPriceMin),
        description: zod.string().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        categories: zod.array(zod.string()).optional(),
        tags: zod.array(zod.string()).optional(),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional(),
        deletedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates an existing product with optional image upload
 * @summary Edit product
 */
export const updateProductBodyPriceMin = 0;

export const UpdateProductBody = zod.strictObject({
    id: zod.string().describe('Resource identifier'),
    title: zod.string(),
    description: zod.string().optional(),
    price: zod.number().min(updateProductBodyPriceMin),
    active: zod.boolean().optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        ),
    categories: zod.array(zod.string()).optional(),
    tags: zod.array(zod.string()).optional()
});

export const updateProductResponseDataPriceMin = 0;

export const UpdateProductResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        title: zod.string(),
        price: zod.number().min(updateProductResponseDataPriceMin),
        description: zod.string().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        categories: zod.array(zod.string()).optional(),
        tags: zod.array(zod.string()).optional(),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional(),
        deletedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Deletes the product identified by the `id` field in the request body. Set `hardDelete` to `true` to permanently remove the record
 * @summary Delete product
 */
export const deleteProductBodyHardDeleteDefault = false;

export const DeleteProductBody = zod.strictObject({
    id: zod.string().describe('Resource identifier'),
    hardDelete: zod.boolean().default(deleteProductBodyHardDeleteDefault)
});

export const DeleteProductResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Returns the full details of the product identified by `{id}`. Functionally equivalent to `GET /products?id={id}`.
 * @summary Product details
 */
export const GetProductByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const getProductByIdResponseDataPriceMin = 0;

export const GetProductByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        title: zod.string(),
        price: zod.number().min(getProductByIdResponseDataPriceMin),
        description: zod.string().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        categories: zod.array(zod.string()).optional(),
        tags: zod.array(zod.string()).optional(),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional(),
        deletedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates the product identified by `{id}` in the path with optional image upload. Functionally equivalent to `PUT /products` with the id in the body.
 * @summary Edit product
 */
export const UpdateProductByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const updateProductByIdBodyPriceMin = 0;

export const UpdateProductByIdBody = zod.strictObject({
    title: zod.string(),
    description: zod.string().optional(),
    price: zod.number().min(updateProductByIdBodyPriceMin),
    active: zod.boolean().optional(),
    imageUrl: zod
        .string()
        .optional()
        .describe(
            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
        ),
    categories: zod.array(zod.string()).optional(),
    tags: zod.array(zod.string()).optional()
});

export const updateProductByIdResponseDataPriceMin = 0;

export const UpdateProductByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        title: zod.string(),
        price: zod.number().min(updateProductByIdResponseDataPriceMin),
        description: zod.string().optional(),
        active: zod.boolean().optional(),
        imageUrl: zod
            .string()
            .optional()
            .describe(
                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
            ),
        categories: zod.array(zod.string()).optional(),
        tags: zod.array(zod.string()).optional(),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional(),
        deletedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Deletes the product identified by `{id}` in the path. Pass the `hardDelete` query parameter as `true` to permanently remove the record. Functionally equivalent to `DELETE /products`.
 * @summary Delete product
 */
export const DeleteProductByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const DeleteProductByIdQueryParams = zod.strictObject({
    hardDelete: zod.boolean().optional()
});

export const DeleteProductByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Searches and filters products via a JSON request body. Functionally equivalent to `GET /products` with query parameters.
 * @summary Search products (DTO-friendly)
 */
export const searchProductsBodyPageDefault = 1;

export const searchProductsBodyPageSizeDefault = 10;
export const searchProductsBodyPageSizeMax = 100;

export const searchProductsBodyMinPriceMin = 0;

export const searchProductsBodyMaxPriceMin = 0;

export const SearchProductsBody = zod.strictObject({
    page: zod.number().min(1).default(searchProductsBodyPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(searchProductsBodyPageSizeMax)
        .default(searchProductsBodyPageSizeDefault)
        .describe('Optional override; server may clamp to a max'),
    text: zod.string().min(1).optional().describe('Free-text search string'),
    id: zod.string().optional().describe('Resource identifier'),
    minPrice: zod.number().min(searchProductsBodyMinPriceMin).optional(),
    maxPrice: zod.number().min(searchProductsBodyMaxPriceMin).optional(),
    category: zod.string().optional(),
    tag: zod.string().optional()
});

export const searchProductsResponseDataItemsItemPriceMin = 0;

export const searchProductsResponseDataMetaPageDefault = 1;

export const searchProductsResponseDataMetaPageSizeDefault = 10;
export const searchProductsResponseDataMetaPageSizeMax = 100;

export const searchProductsResponseDataMetaTotalItemsMin = 0;

export const searchProductsResponseDataMetaTotalPagesMin = 0;

export const SearchProductsResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                title: zod.string(),
                price: zod.number().min(searchProductsResponseDataItemsItemPriceMin),
                description: zod.string().optional(),
                active: zod.boolean().optional(),
                imageUrl: zod
                    .string()
                    .optional()
                    .describe(
                        'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                    ),
                categories: zod.array(zod.string()).optional(),
                tags: zod.array(zod.string()).optional(),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional(),
                deletedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(searchProductsResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(searchProductsResponseDataMetaPageSizeMax)
                .default(searchProductsResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(searchProductsResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(searchProductsResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Returns all items currently in the authenticated user's cart along with a computed summary
 * @summary Get cart
 */

export const getCartResponseDataSummaryItemsCountMin = 0;

export const getCartResponseDataSummaryTotalQuantityMin = 0;

export const getCartResponseDataSummaryTotalMin = 0;

export const GetCartResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        ),
        summary: zod.strictObject({
            itemsCount: zod
                .number()
                .min(getCartResponseDataSummaryItemsCountMin)
                .describe('Number of distinct cart lines\/items'),
            totalQuantity: zod
                .number()
                .min(getCartResponseDataSummaryTotalQuantityMin)
                .describe('Sum of quantities across all items'),
            total: zod
                .number()
                .min(getCartResponseDataSummaryTotalMin)
                .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
            currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
        })
    })
});

/**
 * Adds or edit a product to the authenticated user's cart. Returns the updated cart.
 * @summary Add/Edit cart item
 */

export const UpsertCartItemBody = zod.strictObject({
    productId: zod.string().describe('Resource identifier'),
    quantity: zod.number().min(1)
});

export const upsertCartItemResponseDataSummaryItemsCountMin = 0;

export const upsertCartItemResponseDataSummaryTotalQuantityMin = 0;

export const upsertCartItemResponseDataSummaryTotalMin = 0;

export const UpsertCartItemResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        ),
        summary: zod.strictObject({
            itemsCount: zod
                .number()
                .min(upsertCartItemResponseDataSummaryItemsCountMin)
                .describe('Number of distinct cart lines\/items'),
            totalQuantity: zod
                .number()
                .min(upsertCartItemResponseDataSummaryTotalQuantityMin)
                .describe('Sum of quantities across all items'),
            total: zod
                .number()
                .min(upsertCartItemResponseDataSummaryTotalMin)
                .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
            currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
        })
    })
});

/**
 * Clear cart or, ir productId is set, removes a specific product from the authenticated user's cart. Returns the updated cart (can be empty)
 * @summary Empty cart or, if productId is set, remove target cart item
 */
export const ClearCartBody = zod.strictObject({
    productId: zod.string().optional().describe('Resource identifier')
});

export const clearCartResponseDataSummaryItemsCountMin = 0;

export const clearCartResponseDataSummaryTotalQuantityMin = 0;

export const clearCartResponseDataSummaryTotalMin = 0;

export const ClearCartResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        ),
        summary: zod.strictObject({
            itemsCount: zod
                .number()
                .min(clearCartResponseDataSummaryItemsCountMin)
                .describe('Number of distinct cart lines\/items'),
            totalQuantity: zod
                .number()
                .min(clearCartResponseDataSummaryTotalQuantityMin)
                .describe('Sum of quantities across all items'),
            total: zod
                .number()
                .min(clearCartResponseDataSummaryTotalMin)
                .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
            currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
        })
    })
});

/**
 * Sets the quantity of the cart line for the product identified by `{productId}` in the path. Functionally equivalent to `POST /cart`. Returns the updated cart.
 * @summary Set cart item quantity
 */
export const UpdateCartItemByIdParams = zod.strictObject({
    productId: zod.string().describe('Product identifier')
});

export const UpdateCartItemByIdBody = zod.strictObject({
    productId: zod.string().optional().describe('Resource identifier'),
    quantity: zod.number().min(1)
});

export const updateCartItemByIdResponseDataSummaryItemsCountMin = 0;

export const updateCartItemByIdResponseDataSummaryTotalQuantityMin = 0;

export const updateCartItemByIdResponseDataSummaryTotalMin = 0;

export const UpdateCartItemByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        ),
        summary: zod.strictObject({
            itemsCount: zod
                .number()
                .min(updateCartItemByIdResponseDataSummaryItemsCountMin)
                .describe('Number of distinct cart lines\/items'),
            totalQuantity: zod
                .number()
                .min(updateCartItemByIdResponseDataSummaryTotalQuantityMin)
                .describe('Sum of quantities across all items'),
            total: zod
                .number()
                .min(updateCartItemByIdResponseDataSummaryTotalMin)
                .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
            currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
        })
    })
});

/**
 * Removes the cart line for the product identified by `{productId}` in the path from the authenticated user's cart. Returns the updated cart.
 * @summary Remove item from cart
 */
export const RemoveCartItemParams = zod.strictObject({
    productId: zod.string().describe('Product identifier')
});

export const removeCartItemResponseDataSummaryItemsCountMin = 0;

export const removeCartItemResponseDataSummaryTotalQuantityMin = 0;

export const removeCartItemResponseDataSummaryTotalMin = 0;

export const RemoveCartItemResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        ),
        summary: zod.strictObject({
            itemsCount: zod
                .number()
                .min(removeCartItemResponseDataSummaryItemsCountMin)
                .describe('Number of distinct cart lines\/items'),
            totalQuantity: zod
                .number()
                .min(removeCartItemResponseDataSummaryTotalQuantityMin)
                .describe('Sum of quantities across all items'),
            total: zod
                .number()
                .min(removeCartItemResponseDataSummaryTotalMin)
                .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
            currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
        })
    })
});

/**
 * Returns a lightweight summary of the authenticated user's cart.
 * @summary Get cart summary
 */
export const getCartSummaryResponseDataItemsCountMin = 0;

export const getCartSummaryResponseDataTotalQuantityMin = 0;

export const getCartSummaryResponseDataTotalMin = 0;

export const GetCartSummaryResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        itemsCount: zod
            .number()
            .min(getCartSummaryResponseDataItemsCountMin)
            .describe('Number of distinct cart lines\/items'),
        totalQuantity: zod
            .number()
            .min(getCartSummaryResponseDataTotalQuantityMin)
            .describe('Sum of quantities across all items'),
        total: zod
            .number()
            .min(getCartSummaryResponseDataTotalMin)
            .describe('Sum of item prices \* quantity (before tax\/shipping\/discounts)'),
        currency: zod.string().optional().describe('ISO-4217 currency code (e.g. USD)')
    })
});

/**
 * Converts the authenticated user's current cart into a new order. The cart is cleared upon success. An optional email address and order notes can be supplied in the request body. Returns the created order.
 * @summary Checkout (place order from cart)
 */
export const CheckoutBody = zod.strictObject({
    email: zod.email().optional(),
    notes: zod.string().optional().describe('Optional order notes')
});

export const checkoutResponseDataOrderItemsItemProductPriceMin = 0;

export const checkoutResponseDataOrderTotalItemsMin = 0;

export const checkoutResponseDataOrderTotalQuantityMin = 0;

export const checkoutResponseDataOrderTotalPriceMin = 0;

export const CheckoutResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        order: zod.strictObject({
            id: zod.string().describe('Resource identifier'),
            userId: zod.string().describe('Resource identifier'),
            email: zod.email(),
            items: zod.array(
                zod.strictObject({
                    product: zod.strictObject({
                        id: zod.string().describe('Resource identifier'),
                        title: zod.string(),
                        price: zod.number().min(checkoutResponseDataOrderItemsItemProductPriceMin),
                        description: zod.string().optional(),
                        active: zod.boolean().optional(),
                        imageUrl: zod
                            .string()
                            .optional()
                            .describe(
                                'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                            ),
                        categories: zod.array(zod.string()).optional(),
                        tags: zod.array(zod.string()).optional(),
                        createdAt: zod.iso.datetime({ offset: true }).optional(),
                        updatedAt: zod.iso.datetime({ offset: true }).optional(),
                        deletedAt: zod.iso.datetime({ offset: true }).optional()
                    }),
                    quantity: zod.number().min(1)
                })
            ),
            totalItems: zod
                .number()
                .min(checkoutResponseDataOrderTotalItemsMin)
                .describe(
                    'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
                ),
            totalQuantity: zod
                .number()
                .min(checkoutResponseDataOrderTotalQuantityMin)
                .describe('Sum of `quantity` across every line item.'),
            totalPrice: zod
                .number()
                .min(checkoutResponseDataOrderTotalPriceMin)
                .describe('Sum of `product.price × quantity` across every line item.'),
            notes: zod.string().optional().describe('Optional order notes'),
            status: zod.enum([
                'pending',
                'paid',
                'processing',
                'shipped',
                'delivered',
                'cancelled'
            ]),
            createdAt: zod.iso.datetime({ offset: true }).optional(),
            updatedAt: zod.iso.datetime({ offset: true }).optional()
        }),
        message: zod.string().optional()
    })
});

/**
 * Returns a paginated list of orders.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary List orders (paginated)
 */
export const listOrdersQueryPageDefault = 1;

export const listOrdersQueryPageSizeDefault = 10;
export const listOrdersQueryPageSizeMax = 100;

export const ListOrdersQueryParams = zod.strictObject({
    page: zod.number().min(1).default(listOrdersQueryPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(listOrdersQueryPageSizeMax)
        .default(listOrdersQueryPageSizeDefault),
    id: zod.string().optional(),
    userId: zod.string().optional(),
    productId: zod.string().optional(),
    email: zod.email().optional()
});

export const listOrdersResponseDataItemsItemItemsItemProductPriceMin = 0;

export const listOrdersResponseDataItemsItemTotalItemsMin = 0;

export const listOrdersResponseDataItemsItemTotalQuantityMin = 0;

export const listOrdersResponseDataItemsItemTotalPriceMin = 0;

export const listOrdersResponseDataMetaPageDefault = 1;

export const listOrdersResponseDataMetaPageSizeDefault = 10;
export const listOrdersResponseDataMetaPageSizeMax = 100;

export const listOrdersResponseDataMetaTotalItemsMin = 0;

export const listOrdersResponseDataMetaTotalPagesMin = 0;

export const ListOrdersResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                userId: zod.string().describe('Resource identifier'),
                email: zod.email(),
                items: zod.array(
                    zod.strictObject({
                        product: zod.strictObject({
                            id: zod.string().describe('Resource identifier'),
                            title: zod.string(),
                            price: zod
                                .number()
                                .min(listOrdersResponseDataItemsItemItemsItemProductPriceMin),
                            description: zod.string().optional(),
                            active: zod.boolean().optional(),
                            imageUrl: zod
                                .string()
                                .optional()
                                .describe(
                                    'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                                ),
                            categories: zod.array(zod.string()).optional(),
                            tags: zod.array(zod.string()).optional(),
                            createdAt: zod.iso.datetime({ offset: true }).optional(),
                            updatedAt: zod.iso.datetime({ offset: true }).optional(),
                            deletedAt: zod.iso.datetime({ offset: true }).optional()
                        }),
                        quantity: zod.number().min(1)
                    })
                ),
                totalItems: zod
                    .number()
                    .min(listOrdersResponseDataItemsItemTotalItemsMin)
                    .describe(
                        'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
                    ),
                totalQuantity: zod
                    .number()
                    .min(listOrdersResponseDataItemsItemTotalQuantityMin)
                    .describe('Sum of `quantity` across every line item.'),
                totalPrice: zod
                    .number()
                    .min(listOrdersResponseDataItemsItemTotalPriceMin)
                    .describe('Sum of `product.price × quantity` across every line item.'),
                notes: zod.string().optional().describe('Optional order notes'),
                status: zod.enum([
                    'pending',
                    'paid',
                    'processing',
                    'shipped',
                    'delivered',
                    'cancelled'
                ]),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(listOrdersResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(listOrdersResponseDataMetaPageSizeMax)
                .default(listOrdersResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(listOrdersResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(listOrdersResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Creates a new order directly from the supplied payload.
 * @summary Create order
 */

export const CreateOrderBody = zod
    .strictObject({
        userId: zod.string().describe('Resource identifier'),
        email: zod.email(),
        items: zod
            .array(
                zod.strictObject({
                    productId: zod.string().describe('Resource identifier'),
                    quantity: zod.number().min(1)
                })
            )
            .min(1)
    })
    .describe('Create a new order.');

export const createOrderResponseDataItemsItemProductPriceMin = 0;

export const createOrderResponseDataTotalItemsMin = 0;

export const createOrderResponseDataTotalQuantityMin = 0;

export const createOrderResponseDataTotalPriceMin = 0;

export const CreateOrderResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        userId: zod.string().describe('Resource identifier'),
        email: zod.email(),
        items: zod.array(
            zod.strictObject({
                product: zod.strictObject({
                    id: zod.string().describe('Resource identifier'),
                    title: zod.string(),
                    price: zod.number().min(createOrderResponseDataItemsItemProductPriceMin),
                    description: zod.string().optional(),
                    active: zod.boolean().optional(),
                    imageUrl: zod
                        .string()
                        .optional()
                        .describe(
                            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                        ),
                    categories: zod.array(zod.string()).optional(),
                    tags: zod.array(zod.string()).optional(),
                    createdAt: zod.iso.datetime({ offset: true }).optional(),
                    updatedAt: zod.iso.datetime({ offset: true }).optional(),
                    deletedAt: zod.iso.datetime({ offset: true }).optional()
                }),
                quantity: zod.number().min(1)
            })
        ),
        totalItems: zod
            .number()
            .min(createOrderResponseDataTotalItemsMin)
            .describe(
                'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
            ),
        totalQuantity: zod
            .number()
            .min(createOrderResponseDataTotalQuantityMin)
            .describe('Sum of `quantity` across every line item.'),
        totalPrice: zod
            .number()
            .min(createOrderResponseDataTotalPriceMin)
            .describe('Sum of `product.price × quantity` across every line item.'),
        notes: zod.string().optional().describe('Optional order notes'),
        status: zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates an existing order identified by id in the request body.
 * @summary Update order
 */

export const UpdateOrderBody = zod.strictObject({
    id: zod.string().describe('Resource identifier'),
    status: zod
        .enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled'])
        .optional()
        .describe('Updated order status'),
    userId: zod.string().optional().describe('Resource identifier'),
    email: zod.email().optional(),
    items: zod
        .array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        )
        .min(1)
        .optional()
});

export const updateOrderResponseDataItemsItemProductPriceMin = 0;

export const updateOrderResponseDataTotalItemsMin = 0;

export const updateOrderResponseDataTotalQuantityMin = 0;

export const updateOrderResponseDataTotalPriceMin = 0;

export const UpdateOrderResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        userId: zod.string().describe('Resource identifier'),
        email: zod.email(),
        items: zod.array(
            zod.strictObject({
                product: zod.strictObject({
                    id: zod.string().describe('Resource identifier'),
                    title: zod.string(),
                    price: zod.number().min(updateOrderResponseDataItemsItemProductPriceMin),
                    description: zod.string().optional(),
                    active: zod.boolean().optional(),
                    imageUrl: zod
                        .string()
                        .optional()
                        .describe(
                            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                        ),
                    categories: zod.array(zod.string()).optional(),
                    tags: zod.array(zod.string()).optional(),
                    createdAt: zod.iso.datetime({ offset: true }).optional(),
                    updatedAt: zod.iso.datetime({ offset: true }).optional(),
                    deletedAt: zod.iso.datetime({ offset: true }).optional()
                }),
                quantity: zod.number().min(1)
            })
        ),
        totalItems: zod
            .number()
            .min(updateOrderResponseDataTotalItemsMin)
            .describe(
                'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
            ),
        totalQuantity: zod
            .number()
            .min(updateOrderResponseDataTotalQuantityMin)
            .describe('Sum of `quantity` across every line item.'),
        totalPrice: zod
            .number()
            .min(updateOrderResponseDataTotalPriceMin)
            .describe('Sum of `product.price × quantity` across every line item.'),
        notes: zod.string().optional().describe('Optional order notes'),
        status: zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Permanently removes the order identified by id.
 * @summary Delete order
 */
export const DeleteOrderBody = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const DeleteOrderResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Searches and filters orders via a JSON request body. Functionally equivalent to `GET /orders`.
 * Non-admin users are automatically scoped to their own orders; the `userId` filter is ignored for non-admin callers.
 * @summary Search orders (DTO-friendly)
 */
export const searchOrdersBodyPageDefault = 1;

export const searchOrdersBodyPageSizeDefault = 10;
export const searchOrdersBodyPageSizeMax = 100;

export const SearchOrdersBody = zod.strictObject({
    page: zod.number().min(1).default(searchOrdersBodyPageDefault).describe('1-based page index'),
    pageSize: zod
        .number()
        .min(1)
        .max(searchOrdersBodyPageSizeMax)
        .default(searchOrdersBodyPageSizeDefault)
        .describe('Optional override; server may clamp to a max'),
    id: zod.string().optional().describe('Resource identifier'),
    userId: zod.string().optional().describe('Resource identifier'),
    productId: zod.string().optional().describe('Resource identifier'),
    email: zod.email().optional()
});

export const searchOrdersResponseDataItemsItemItemsItemProductPriceMin = 0;

export const searchOrdersResponseDataItemsItemTotalItemsMin = 0;

export const searchOrdersResponseDataItemsItemTotalQuantityMin = 0;

export const searchOrdersResponseDataItemsItemTotalPriceMin = 0;

export const searchOrdersResponseDataMetaPageDefault = 1;

export const searchOrdersResponseDataMetaPageSizeDefault = 10;
export const searchOrdersResponseDataMetaPageSizeMax = 100;

export const searchOrdersResponseDataMetaTotalItemsMin = 0;

export const searchOrdersResponseDataMetaTotalPagesMin = 0;

export const SearchOrdersResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        items: zod.array(
            zod.strictObject({
                id: zod.string().describe('Resource identifier'),
                userId: zod.string().describe('Resource identifier'),
                email: zod.email(),
                items: zod.array(
                    zod.strictObject({
                        product: zod.strictObject({
                            id: zod.string().describe('Resource identifier'),
                            title: zod.string(),
                            price: zod
                                .number()
                                .min(searchOrdersResponseDataItemsItemItemsItemProductPriceMin),
                            description: zod.string().optional(),
                            active: zod.boolean().optional(),
                            imageUrl: zod
                                .string()
                                .optional()
                                .describe(
                                    'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                                ),
                            categories: zod.array(zod.string()).optional(),
                            tags: zod.array(zod.string()).optional(),
                            createdAt: zod.iso.datetime({ offset: true }).optional(),
                            updatedAt: zod.iso.datetime({ offset: true }).optional(),
                            deletedAt: zod.iso.datetime({ offset: true }).optional()
                        }),
                        quantity: zod.number().min(1)
                    })
                ),
                totalItems: zod
                    .number()
                    .min(searchOrdersResponseDataItemsItemTotalItemsMin)
                    .describe(
                        'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
                    ),
                totalQuantity: zod
                    .number()
                    .min(searchOrdersResponseDataItemsItemTotalQuantityMin)
                    .describe('Sum of `quantity` across every line item.'),
                totalPrice: zod
                    .number()
                    .min(searchOrdersResponseDataItemsItemTotalPriceMin)
                    .describe('Sum of `product.price × quantity` across every line item.'),
                notes: zod.string().optional().describe('Optional order notes'),
                status: zod.enum([
                    'pending',
                    'paid',
                    'processing',
                    'shipped',
                    'delivered',
                    'cancelled'
                ]),
                createdAt: zod.iso.datetime({ offset: true }).optional(),
                updatedAt: zod.iso.datetime({ offset: true }).optional()
            })
        ),
        meta: zod.strictObject({
            page: zod
                .number()
                .min(1)
                .default(searchOrdersResponseDataMetaPageDefault)
                .describe('1-based page index'),
            pageSize: zod
                .number()
                .min(1)
                .max(searchOrdersResponseDataMetaPageSizeMax)
                .default(searchOrdersResponseDataMetaPageSizeDefault)
                .describe('Optional override; server may clamp to a max'),
            totalItems: zod.number().min(searchOrdersResponseDataMetaTotalItemsMin),
            totalPages: zod.number().min(searchOrdersResponseDataMetaTotalPagesMin)
        })
    })
});

/**
 * Returns the full details of the order identified by `{id}`. Functionally equivalent to `GET /orders?id={id}`.
 * @summary Order details
 */
export const GetOrderByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const getOrderByIdResponseDataItemsItemProductPriceMin = 0;

export const getOrderByIdResponseDataTotalItemsMin = 0;

export const getOrderByIdResponseDataTotalQuantityMin = 0;

export const getOrderByIdResponseDataTotalPriceMin = 0;

export const GetOrderByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        userId: zod.string().describe('Resource identifier'),
        email: zod.email(),
        items: zod.array(
            zod.strictObject({
                product: zod.strictObject({
                    id: zod.string().describe('Resource identifier'),
                    title: zod.string(),
                    price: zod.number().min(getOrderByIdResponseDataItemsItemProductPriceMin),
                    description: zod.string().optional(),
                    active: zod.boolean().optional(),
                    imageUrl: zod
                        .string()
                        .optional()
                        .describe(
                            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                        ),
                    categories: zod.array(zod.string()).optional(),
                    tags: zod.array(zod.string()).optional(),
                    createdAt: zod.iso.datetime({ offset: true }).optional(),
                    updatedAt: zod.iso.datetime({ offset: true }).optional(),
                    deletedAt: zod.iso.datetime({ offset: true }).optional()
                }),
                quantity: zod.number().min(1)
            })
        ),
        totalItems: zod
            .number()
            .min(getOrderByIdResponseDataTotalItemsMin)
            .describe(
                'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
            ),
        totalQuantity: zod
            .number()
            .min(getOrderByIdResponseDataTotalQuantityMin)
            .describe('Sum of `quantity` across every line item.'),
        totalPrice: zod
            .number()
            .min(getOrderByIdResponseDataTotalPriceMin)
            .describe('Sum of `product.price × quantity` across every line item.'),
        notes: zod.string().optional().describe('Optional order notes'),
        status: zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Updates the order identified by `{id}` in the path.
 * @summary Edit order
 */
export const UpdateOrderByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const UpdateOrderByIdBody = zod.strictObject({
    status: zod
        .enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled'])
        .optional()
        .describe('Updated order status'),
    userId: zod.string().optional().describe('Resource identifier'),
    email: zod.email().optional(),
    items: zod
        .array(
            zod.strictObject({
                productId: zod.string().describe('Resource identifier'),
                quantity: zod.number().min(1)
            })
        )
        .min(1)
        .optional()
});

export const updateOrderByIdResponseDataItemsItemProductPriceMin = 0;

export const updateOrderByIdResponseDataTotalItemsMin = 0;

export const updateOrderByIdResponseDataTotalQuantityMin = 0;

export const updateOrderByIdResponseDataTotalPriceMin = 0;

export const UpdateOrderByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string(),
    data: zod.strictObject({
        id: zod.string().describe('Resource identifier'),
        userId: zod.string().describe('Resource identifier'),
        email: zod.email(),
        items: zod.array(
            zod.strictObject({
                product: zod.strictObject({
                    id: zod.string().describe('Resource identifier'),
                    title: zod.string(),
                    price: zod.number().min(updateOrderByIdResponseDataItemsItemProductPriceMin),
                    description: zod.string().optional(),
                    active: zod.boolean().optional(),
                    imageUrl: zod
                        .string()
                        .optional()
                        .describe(
                            'Absolute URL or server-relative upload path (e.g. `\/uploads\/abc.jpg`). `uri-reference`, not `uri`: an uploaded image is stored and returned as a path relative to the API host, which is not a valid absolute URI.'
                        ),
                    categories: zod.array(zod.string()).optional(),
                    tags: zod.array(zod.string()).optional(),
                    createdAt: zod.iso.datetime({ offset: true }).optional(),
                    updatedAt: zod.iso.datetime({ offset: true }).optional(),
                    deletedAt: zod.iso.datetime({ offset: true }).optional()
                }),
                quantity: zod.number().min(1)
            })
        ),
        totalItems: zod
            .number()
            .min(updateOrderByIdResponseDataTotalItemsMin)
            .describe(
                'Number of distinct line items in this order. Not to be confused with `PaginationMeta.totalItems`, which counts orders matching a search.'
            ),
        totalQuantity: zod
            .number()
            .min(updateOrderByIdResponseDataTotalQuantityMin)
            .describe('Sum of `quantity` across every line item.'),
        totalPrice: zod
            .number()
            .min(updateOrderByIdResponseDataTotalPriceMin)
            .describe('Sum of `product.price × quantity` across every line item.'),
        notes: zod.string().optional().describe('Optional order notes'),
        status: zod.enum(['pending', 'paid', 'processing', 'shipped', 'delivered', 'cancelled']),
        createdAt: zod.iso.datetime({ offset: true }).optional(),
        updatedAt: zod.iso.datetime({ offset: true }).optional()
    })
});

/**
 * Permanently removes the order identified by `id`.
 * @summary Delete order
 */
export const DeleteOrderByIdParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const DeleteOrderByIdResponse = zod.strictObject({
    success: zod.literal(true),
    status: zod.number(),
    message: zod.string()
});

/**
 * Generates and returns the invoice for the order identified by `{id}` as a binary PDF file. The client should save or stream the response with an appropriate `Content-Disposition` header.
 * @summary Download order invoice (PDF)
 */
export const GetOrderInvoiceParams = zod.strictObject({
    id: zod.string().describe('Resource identifier')
});

export const GetOrderInvoiceResponse = zod.unknown();
